# Generated parameter bindings for the IQ64 IP.
proc init_gui { IPINST } {
  ipgui::add_param $IPINST -name "Component_Name"
  ipgui::add_param $IPINST -name "S_AXIS_DATA_WIDTH"
  ipgui::add_param $IPINST -name "M_AXIS_DATA_WIDTH"
  ipgui::add_param $IPINST -name "LANE_WIDTH"
  ipgui::add_param $IPINST -name "DECIM0"
  ipgui::add_param $IPINST -name "DECIM1"
  ipgui::add_param $IPINST -name "DECIM2"
  ipgui::add_param $IPINST -name "COEF_WIDTH_PARAM"
  ipgui::add_param $IPINST -name "ACC_WIDTH"
  ipgui::add_param $IPINST -name "OUT_WIDTH"
  ipgui::add_param $IPINST -name "OUTPUT_SCALE_LOG2"
  ipgui::add_param $IPINST -name "FORMAT_VERSION"
  ipgui::add_param $IPINST -name "PIPELINE_LATENCY_CYCLES"
}
proc update_PARAM_VALUE.S_AXIS_DATA_WIDTH { PARAM_VALUE.S_AXIS_DATA_WIDTH } {}
proc validate_PARAM_VALUE.S_AXIS_DATA_WIDTH { PARAM_VALUE.S_AXIS_DATA_WIDTH } { return true }
proc update_MODELPARAM_VALUE.S_AXIS_DATA_WIDTH { MODELPARAM_VALUE.S_AXIS_DATA_WIDTH PARAM_VALUE.S_AXIS_DATA_WIDTH } {
  set_property value [get_property value ${PARAM_VALUE.S_AXIS_DATA_WIDTH}] ${MODELPARAM_VALUE.S_AXIS_DATA_WIDTH}
}
proc update_PARAM_VALUE.M_AXIS_DATA_WIDTH { PARAM_VALUE.M_AXIS_DATA_WIDTH } {}
proc validate_PARAM_VALUE.M_AXIS_DATA_WIDTH { PARAM_VALUE.M_AXIS_DATA_WIDTH } { return true }
proc update_MODELPARAM_VALUE.M_AXIS_DATA_WIDTH { MODELPARAM_VALUE.M_AXIS_DATA_WIDTH PARAM_VALUE.M_AXIS_DATA_WIDTH } {
  set_property value [get_property value ${PARAM_VALUE.M_AXIS_DATA_WIDTH}] ${MODELPARAM_VALUE.M_AXIS_DATA_WIDTH}
}
proc update_PARAM_VALUE.LANE_WIDTH { PARAM_VALUE.LANE_WIDTH } {}
proc validate_PARAM_VALUE.LANE_WIDTH { PARAM_VALUE.LANE_WIDTH } { return true }
proc update_MODELPARAM_VALUE.LANE_WIDTH { MODELPARAM_VALUE.LANE_WIDTH PARAM_VALUE.LANE_WIDTH } {
  set_property value [get_property value ${PARAM_VALUE.LANE_WIDTH}] ${MODELPARAM_VALUE.LANE_WIDTH}
}
proc update_PARAM_VALUE.DECIM0 { PARAM_VALUE.DECIM0 } {}
proc validate_PARAM_VALUE.DECIM0 { PARAM_VALUE.DECIM0 } { return true }
proc update_MODELPARAM_VALUE.DECIM0 { MODELPARAM_VALUE.DECIM0 PARAM_VALUE.DECIM0 } {
  set_property value [get_property value ${PARAM_VALUE.DECIM0}] ${MODELPARAM_VALUE.DECIM0}
}
proc update_PARAM_VALUE.DECIM1 { PARAM_VALUE.DECIM1 } {}
proc validate_PARAM_VALUE.DECIM1 { PARAM_VALUE.DECIM1 } { return true }
proc update_MODELPARAM_VALUE.DECIM1 { MODELPARAM_VALUE.DECIM1 PARAM_VALUE.DECIM1 } {
  set_property value [get_property value ${PARAM_VALUE.DECIM1}] ${MODELPARAM_VALUE.DECIM1}
}
proc update_PARAM_VALUE.DECIM2 { PARAM_VALUE.DECIM2 } {}
proc validate_PARAM_VALUE.DECIM2 { PARAM_VALUE.DECIM2 } { return true }
proc update_MODELPARAM_VALUE.DECIM2 { MODELPARAM_VALUE.DECIM2 PARAM_VALUE.DECIM2 } {
  set_property value [get_property value ${PARAM_VALUE.DECIM2}] ${MODELPARAM_VALUE.DECIM2}
}
proc update_PARAM_VALUE.COEF_WIDTH_PARAM { PARAM_VALUE.COEF_WIDTH_PARAM } {}
proc validate_PARAM_VALUE.COEF_WIDTH_PARAM { PARAM_VALUE.COEF_WIDTH_PARAM } { return true }
proc update_MODELPARAM_VALUE.COEF_WIDTH_PARAM { MODELPARAM_VALUE.COEF_WIDTH_PARAM PARAM_VALUE.COEF_WIDTH_PARAM } {
  set_property value [get_property value ${PARAM_VALUE.COEF_WIDTH_PARAM}] ${MODELPARAM_VALUE.COEF_WIDTH_PARAM}
}
proc update_PARAM_VALUE.ACC_WIDTH { PARAM_VALUE.ACC_WIDTH } {}
proc validate_PARAM_VALUE.ACC_WIDTH { PARAM_VALUE.ACC_WIDTH } { return true }
proc update_MODELPARAM_VALUE.ACC_WIDTH { MODELPARAM_VALUE.ACC_WIDTH PARAM_VALUE.ACC_WIDTH } {
  set_property value [get_property value ${PARAM_VALUE.ACC_WIDTH}] ${MODELPARAM_VALUE.ACC_WIDTH}
}
proc update_PARAM_VALUE.OUT_WIDTH { PARAM_VALUE.OUT_WIDTH } {}
proc validate_PARAM_VALUE.OUT_WIDTH { PARAM_VALUE.OUT_WIDTH } { return true }
proc update_MODELPARAM_VALUE.OUT_WIDTH { MODELPARAM_VALUE.OUT_WIDTH PARAM_VALUE.OUT_WIDTH } {
  set_property value [get_property value ${PARAM_VALUE.OUT_WIDTH}] ${MODELPARAM_VALUE.OUT_WIDTH}
}
proc update_PARAM_VALUE.OUTPUT_SCALE_LOG2 { PARAM_VALUE.OUTPUT_SCALE_LOG2 } {}
proc validate_PARAM_VALUE.OUTPUT_SCALE_LOG2 { PARAM_VALUE.OUTPUT_SCALE_LOG2 } { return true }
proc update_MODELPARAM_VALUE.OUTPUT_SCALE_LOG2 { MODELPARAM_VALUE.OUTPUT_SCALE_LOG2 PARAM_VALUE.OUTPUT_SCALE_LOG2 } {
  set_property value [get_property value ${PARAM_VALUE.OUTPUT_SCALE_LOG2}] ${MODELPARAM_VALUE.OUTPUT_SCALE_LOG2}
}
proc update_PARAM_VALUE.FORMAT_VERSION { PARAM_VALUE.FORMAT_VERSION } {}
proc validate_PARAM_VALUE.FORMAT_VERSION { PARAM_VALUE.FORMAT_VERSION } { return true }
proc update_MODELPARAM_VALUE.FORMAT_VERSION { MODELPARAM_VALUE.FORMAT_VERSION PARAM_VALUE.FORMAT_VERSION } {
  set_property value [get_property value ${PARAM_VALUE.FORMAT_VERSION}] ${MODELPARAM_VALUE.FORMAT_VERSION}
}
proc update_PARAM_VALUE.PIPELINE_LATENCY_CYCLES { PARAM_VALUE.PIPELINE_LATENCY_CYCLES } {}
proc validate_PARAM_VALUE.PIPELINE_LATENCY_CYCLES { PARAM_VALUE.PIPELINE_LATENCY_CYCLES } { return true }
proc update_MODELPARAM_VALUE.PIPELINE_LATENCY_CYCLES { MODELPARAM_VALUE.PIPELINE_LATENCY_CYCLES PARAM_VALUE.PIPELINE_LATENCY_CYCLES } {
  set_property value [get_property value ${PARAM_VALUE.PIPELINE_LATENCY_CYCLES}] ${MODELPARAM_VALUE.PIPELINE_LATENCY_CYCLES}
}
