"""
Driver helpers for ``axis_awg_tuning_v1``.

``axis_awg_tuning_v1`` is an AXIS-command-controlled continuous DAC sample
source. The tProcessor AXIS command path remains the normal SET/RAMP control
path. The IP also exposes a minimal AXI-Lite register pair for software/debug
current-output override and readback only; AXI-Lite does not execute SET/RAMP
commands or provide ramp duration/start/step controls.

The current RTL has these software-visible semantics:

* ``s_axis_tready`` is always asserted.
* ``m_axis_tready`` is ignored by the RTL.
* ``m_axis_tvalid`` remains asserted after reset.
* SET changes the current output immediately.
* RAMP starts from the internal current output and uses target/duration plus
  the command-provided signed 24-bit fixed-point step field in bits 119:96.
* The command start field is reserved/deprecated and ignored by RTL.
* RTL does not calculate the RAMP step or infer a divider; software must pack
  the desired step into the command.
* RAMP output starts after a DSP pipeline latency of
  ``EXTRA_Y_PIPE_STAGES + 4`` cycles.
* RFDC-facing output words are 16-bit DAC codes with 14 effective MSB-aligned
  bits; hardware clears bits 1:0 of every output lane.
* Commands presented during an active ramp are dropped by hardware.
* Timed IDLE is not supported unless explicitly reintroduced in RTL.

Software/tProcessor programs must schedule meaningful commands so they are not
emitted during ``RAMP_ST`` unless intentional discard is desired. The
software-side ``current_value`` cache is only a convenience for prediction and
sequence construction. It can be wrong if another tProcessor program emits
commands not generated by this driver; call :meth:`reset_cache` when software
and hardware state may have diverged.
"""

import csv
import math
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np

from qick.drivers.generator import AbsPulsedSignalGen


class AxisAwgTuningV1(AbsPulsedSignalGen):
    """Python helper driver for the AWG tuning IP.

    Use :meth:`pack_cmd` or the opcode-specific helpers to generate SET/RAMP
    command words for a tProcessor program or another firmware command source.
    Use :meth:`override_current` only for direct software/debug current-output
    override through AXI-Lite.
    """

    bindto = [
        "QICK:QICK:axis_awg_tuning_v1:1.0",
        "user.org:user:axis_awg_tuning_v1:1.0",
    ]

    TPROC_PORT = "s_axis"
    OUTPUT_PORT = "m_axis"

    HAS_MIXER = False
    HAS_DDS = False
    B_DDS = 32
    B_PHASE = 32
    MAXV = (2**15 - 1) & ~0x3

    OP_NOP = 0b00
    OP_SET = 0b01
    OP_RAMP = 0b10
    OP_IDLE = 0b11

    HAS_IDLE = False
    CONTINUOUS_RAMP = True
    CONTINUOUS_OUTPUT = True
    CMD_READY_ALWAYS = True
    OUTPUT_READY_IGNORED = True
    DROPS_COMMANDS_WHILE_RAMPING = True
    HAS_TIMED_IDLE = False
    STEP_WIDTH = 24
    DURATION_WIDTH = 23
    DAC_WORD_BITS = 16
    DAC_EFFECTIVE_BITS = 14
    EXTRA_Y_PIPE_STAGES_DEFAULT = 1
    RAMP_STARTUP_LATENCY_CYCLES = EXTRA_Y_PIPE_STAGES_DEFAULT + 4

    FIELD_MIN = -(2**31)
    FIELD_MAX = 2**31 - 1
    U32_MAX = 2**32 - 1
    STEP_MIN = -(2 ** (STEP_WIDTH - 1))
    STEP_MAX = 2 ** (STEP_WIDTH - 1) - 1
    DURATION_MAX = 2 ** DURATION_WIDTH - 1

    def _init_config(self, description):
        """Read IP parameters from the overlay description."""
        self.REGISTERS = {
            "current_value_reg": 0,
            "status_reg": 1,
        }
        super()._init_config(description)

        params = description.get("parameters", {})
        if "N_PTS" in params:
            n_pts = self._param_int(params, "N_PTS", 16)
        else:
            n_pts = self._param_int(params, "N_DDS", 16)
        b = self._param_int(params, "B", 16)
        frac = self._param_int(params, "FRAC", 16)
        cmd_width = self._param_int(params, "CMD_WIDTH", 160)
        step_width = self._param_int(params, "STEP_WIDTH", self.STEP_WIDTH)
        duration_width = self._param_int(params, "DURATION_WIDTH", self.DURATION_WIDTH)
        fixed_width = self._param_int(params, "FIXED_WIDTH", 48)
        extra_y_pipe_stages = self._param_int(
            params, "EXTRA_Y_PIPE_STAGES", self.EXTRA_Y_PIPE_STAGES_DEFAULT
        )

        if cmd_width < 149:
            raise ValueError("axis_awg_tuning_v1 command width must include bits through 148")
        if step_width != self.STEP_WIDTH:
            raise ValueError("axis_awg_tuning_v1 currently expects STEP_WIDTH=24")
        if duration_width != self.DURATION_WIDTH:
            raise ValueError("axis_awg_tuning_v1 currently expects DURATION_WIDTH=23")

        dac_invalid_lsb = b - self.DAC_EFFECTIVE_BITS
        if dac_invalid_lsb < 0:
            raise ValueError("DAC effective bits cannot exceed output word bits")
        dac_lsb_mask = (1 << dac_invalid_lsb) - 1

        self.cfg["n_pts"] = n_pts
        self.cfg["samps_per_clk"] = n_pts
        self.cfg["b"] = b
        self.cfg["frac"] = frac
        self.cfg["cmd_width"] = cmd_width
        self.cfg["step_width"] = step_width
        self.cfg["duration_width"] = duration_width
        self.cfg["fixed_width"] = fixed_width
        self.cfg["dac_word_bits"] = self.DAC_WORD_BITS
        self.cfg["dac_effective_bits"] = self.DAC_EFFECTIVE_BITS
        self.cfg["dac_invalid_lsb"] = dac_invalid_lsb
        self.cfg["extra_y_pipe_stages"] = extra_y_pipe_stages
        self.cfg["maxv"] = (2 ** (b - 1) - 1) & ~dac_lsb_mask
        self.cfg["minv"] = -(2 ** (b - 1))
        self.cfg["gen_type"] = "awg_tuning"
        self.cfg["has_idle"] = self.HAS_IDLE
        self.cfg["continuous_ramp"] = self.CONTINUOUS_RAMP
        self.cfg["continuous_output"] = self.CONTINUOUS_OUTPUT
        self.cfg["cmd_ready_always"] = self.CMD_READY_ALWAYS
        self.cfg["output_ready_ignored"] = self.OUTPUT_READY_IGNORED
        self.cfg["drops_commands_while_ramping"] = self.DROPS_COMMANDS_WHILE_RAMPING
        self.cfg["has_timed_idle"] = self.HAS_TIMED_IDLE
        self.cfg["ramp_startup_latency_cycles"] = extra_y_pipe_stages + 4
        self.cfg["ramp_guard_cycles"] = 1
        self.cfg.setdefault("tproc_ch", None)
        self.cfg["tproc_port"] = None
        self.cfg["tproc_block"] = None
        self.cfg["tproc_type"] = None
        self.cfg["downstream"] = None

    def _init_firmware(self):
        """Initialize software-only cached state without changing hardware."""
        self.current_value = 0
        self.current_valid = False
        self.last_ramp_start = None
        self.last_ramp_step = None

    @staticmethod
    def _param_int(params, name, default):
        value = params.get(name, default)
        if isinstance(value, str):
            return int(value, 0)
        return int(value)

    def configure_connections(self, soc):
        """Discover tProcessor input and downstream output connections.

        The metadata walk follows the same broad pattern as
        ``AbsPulsedSignalGen.configure_connections``. Standard generator
        tracing fills ``dac``, RFDC timing fields, ``tproc_ch``, and optional
        ``tmux_ch``. Extra AWG debug fields are best-effort only.
        """
        super().configure_connections(soc)
        self.soc = soc

        try:
            trace_result = soc.metadata.trace_back(
                self["fullpath"],
                self.TPROC_PORT,
                ["axis_tproc64x32_x8", "qick_processor", "axis_tmux_v1"],
            )
            if trace_result is not None:
                block, port, blocktype = trace_result

                if blocktype == "axis_tmux_v1":
                    self.cfg["tmux_ch"] = int(port.split("_")[0][1:])
                    ((block, port),) = soc.metadata.trace_bus(block, "s_axis")
                    blocktype = soc.metadata.mod2type(block)

                self.cfg["tproc_block"] = block
                self.cfg["tproc_port"] = port
                self.cfg["tproc_type"] = blocktype

                tproc = soc._get_block(block)
                if hasattr(tproc, "port2ch"):
                    self.cfg["tproc_ch"], _ = tproc.port2ch(port)
        except Exception as exc:
            self.logger.warning("could not collect AWG tuning tProcessor debug fields: %s", exc)

        try:
            peers = soc.metadata.trace_bus(self["fullpath"], self.OUTPUT_PORT)
            downstream = []
            for peer in peers:
                if len(peer) == 2:
                    block, port = peer
                    try:
                        blocktype = soc.metadata.mod2type(block)
                    except Exception:
                        blocktype = None
                    downstream.append((block, port, blocktype))
                else:
                    downstream.append(tuple(peer))
            self.cfg["downstream"] = downstream
            self.cfg["output"] = downstream
        except Exception as exc:
            self.logger.warning("could not trace AWG tuning output connection: %s", exc)

    def _check_int(self, value, name):
        """Return ``value`` as a Python int, rejecting booleans/non-integers."""
        if isinstance(value, (bool, np.bool_)) or not isinstance(value, (int, np.integer)):
            raise ValueError(f"{name} must be an integer")
        return int(value)

    def _to_u32_signed(self, value, name):
        """Convert a signed 32-bit field to unsigned two's-complement form."""
        value = self._check_int(value, name)
        if value < self.FIELD_MIN or value > self.FIELD_MAX:
            raise ValueError(f"{name}={value} does not fit in signed 32 bits")
        return value & self.U32_MAX

    def _to_u32_unsigned(self, value, name):
        """Validate and convert an unsigned 32-bit field."""
        value = self._check_int(value, name)
        if value < 0 or value > self.U32_MAX:
            raise ValueError(f"{name}={value} does not fit in unsigned 32 bits")
        return value

    def _to_duration_field(self, value, name):
        """Validate and convert an unsigned 23-bit RAMP duration field."""
        value = self._check_int(value, name)
        if value < 0 or value > self.DURATION_MAX:
            raise ValueError(f"{name}={value} does not fit in unsigned {self.DURATION_WIDTH} bits")
        return value

    def _to_step_field(self, value, name):
        """Validate and convert a signed 24-bit RAMP step field."""
        value = self._check_int(value, name)
        if value < self.STEP_MIN or value > self.STEP_MAX:
            raise ValueError(f"{name}={value} does not fit in signed {self.STEP_WIDTH} bits")
        return value & ((1 << self.STEP_WIDTH) - 1)

    def _check_bool(self, value, name):
        if not isinstance(value, (bool, np.bool_)):
            raise ValueError(f"{name} must be a bool")
        return bool(value)

    @staticmethod
    def _from_u32_signed(value):
        value &= 0xFFFFFFFF
        if value & 0x80000000:
            return value - 0x100000000
        return value

    @staticmethod
    def _from_signed_field(value, width):
        mask = (1 << width) - 1
        sign = 1 << (width - 1)
        value &= mask
        if value & sign:
            return value - (1 << width)
        return value

    def override_current(self, value, *, saturate=False):
        """Override the current output value through AXI-Lite.

        This is a debug/software override of ``CURRENT_VALUE_REG``. Hardware
        aborts any active ramp, forces the FSM back to IDLE_ST, and holds the
        written scalar value replicated across all ``N_PTS`` output lanes. It
        does not use the AXIS command parser.
        """
        value = self._check_int(value, "value")
        if saturate:
            value = self.clip_sample(value)
        self.current_value_reg = self._to_u32_signed(value, "value")
        self.current_value = value
        self.current_valid = True
        self.last_ramp_start = None
        self.last_ramp_step = None

    def get_current(self):
        """Read CURRENT_VALUE_REG as a signed 32-bit current output value."""
        return self._from_u32_signed(int(self.current_value_reg))

    def get_status(self, decode=False):
        """Read STATUS_REG.

        When ``decode`` is false, return the raw 32-bit integer. When true,
        return a small dictionary for the implemented status bits.
        """
        status = int(self.status_reg) & 0xFFFFFFFF
        if not decode:
            return status
        return {
            "raw": status,
            "idle": bool(status & 0x1),
            "ramping": bool(status & 0x2),
            "m_axis_tvalid": bool(status & 0x4),
            "s_axis_tready": bool(status & 0x8),
            "axi_override_pending": bool(status & 0x10),
            "axi_override_seen": bool(status & 0x20),
        }

    def is_ramping(self):
        """Return True when STATUS_REG indicates RAMP_ST."""
        return bool(self.get_status() & 0x2)

    @staticmethod
    def _div_trunc_zero(num, den):
        """Signed integer division matching SystemVerilog truncation to zero."""
        if den == 0:
            raise ZeroDivisionError("division by zero")
        sign = -1 if (num < 0) ^ (den < 0) else 1
        return sign * (abs(num) // abs(den))

    def clip_sample(self, value):
        """Clip and quantize a value to 16-bit, 14-effective-bit DAC range."""
        value = self._check_int(value, "value")
        value = max(self["minv"], min(self["maxv"], value))
        if self["dac_invalid_lsb"]:
            value &= ~((1 << self["dac_invalid_lsb"]) - 1)
        return value

    def calc_step(self, start, target, duration):
        """Calculate the signed fixed-point RAMP step packed into a command.

        Python ``//`` floors negative divisions, but SystemVerilog signed
        division truncates toward zero. This helper uses truncation toward zero
        to match the existing command-generation policy and testbench.
        ``ramp_cmd`` packs the returned value into bits 119:96. The RTL uses
        that field directly and does not calculate a step internally.
        """
        start = self._check_int(start, "start")
        target = self._check_int(target, "target")
        duration = self._to_duration_field(duration, "duration")
        self._to_u32_signed(start, "start")
        self._to_u32_signed(target, "target")

        duration = 1 if duration == 0 else duration
        n_scalar_samples = duration * int(self["n_pts"])
        if n_scalar_samples <= 1:
            return 0

        numerator = (target - start) << self["frac"]
        step = self._div_trunc_zero(numerator, n_scalar_samples - 1)
        self._to_step_field(step, "step")
        return step

    def _duration_cycles_to_command_samples(self, duration, name):
        duration = self._to_duration_field(duration, name)
        effective_duration = 1 if duration == 0 else duration
        command_duration = effective_duration * int(self["n_pts"])
        self._to_duration_field(command_duration, f"{name} command sample count")
        return command_duration

    def pack_cmd(self, target=0, start=0, duration=0, step=0,
                 opcode=None, hold_zero=False, clear=False):
        """Pack a 160-bit AWG tuning command word into a Python int.

        This low-level packer includes all fields, including the ignored RAMP
        start field and the RAMP step field. For normal use, call
        :meth:`set_cmd` or :meth:`ramp_cmd`. The current RTL ignores the RAMP
        start field, starts from its internal current value, and uses the
        command-provided step field directly.
        """
        if opcode is None:
            opcode = self.OP_NOP

        target_u = self._to_u32_signed(target, "target")
        start_u = self._to_u32_signed(start, "reserved_start")
        duration_u = self._to_duration_field(duration, "duration")
        step_u = self._to_step_field(step, "step")
        opcode = self._check_int(opcode, "opcode")
        if opcode < 0 or opcode > 0b11:
            raise ValueError("opcode must fit in 2 bits")
        hold_zero = self._check_bool(hold_zero, "hold_zero")
        clear = self._check_bool(clear, "clear")

        cmd = 0
        cmd |= target_u
        cmd |= start_u << 32
        cmd |= duration_u << 64
        cmd |= step_u << 96
        cmd |= opcode << 144
        cmd |= int(hold_zero) << 146
        cmd |= int(clear) << 148

        if cmd >= (1 << self["cmd_width"]):
            raise ValueError("packed command exceeds configured CMD_WIDTH")
        return cmd

    def nop_cmd(self, clear=False):
        """Return a NOP command word.

        In the current RTL, NOP is immediate and does not modify current value.
        The ``clear`` bit is packed if requested but is ignored by the RTL.
        """
        return self.pack_cmd(opcode=self.OP_NOP, clear=clear)

    def set_cmd(self, output_value, *, hold_zero=False, clear=False, saturate=False):
        """Return a SET command word and update the software cache.

        ``output_value`` is a signed 32-bit logical target. If
        ``saturate=True``, the value is first clipped to the configured output
        sample range. ``hold_zero`` matches the current RTL SET behavior: the
        SET word emits ``output_value``, then the held output becomes zero.
        ``clear`` is packed for field visibility but is ignored by current RTL.
        """
        value = self._check_int(output_value, "output_value")
        if saturate:
            value = self.clip_sample(value)
        self._to_u32_signed(value, "output_value")

        cmd = self.pack_cmd(target=value, opcode=self.OP_SET,
                            hold_zero=hold_zero, clear=clear)
        self.current_value = 0 if hold_zero else value
        self.current_valid = True
        return cmd

    def ramp_cmd(self, final_output_value, ramp_duration, *, step=None,
                 hold_zero=False, clear=False):
        """Return a RAMP command word and update the software cache.

        This AXIS command helper exposes only the final output value and fabric-cycle
        duration by default. The effective ramp starts from the IP's internal
        current output. This method uses the software ``current_value`` cache to
        calculate the command step unless an explicit ``step`` is supplied.

        Commands issued during an active ramp are dropped by hardware. This
        method only packs a command word; it does not schedule tProcessor
        timing.
        """
        if hold_zero:
            raise NotImplementedError("RAMP hold_zero is not implemented by the current RTL")

        target = self._check_int(final_output_value, "final_output_value")
        duration = self._to_duration_field(ramp_duration, "ramp_duration")
        command_duration = self._duration_cycles_to_command_samples(duration, "ramp_duration")
        self._to_u32_signed(target, "final_output_value")

        if not self.current_valid:
            raise ValueError(
                "software current-value cache is invalid; call reset_cache(value, valid=True) "
                "or issue a SET command through this driver before creating a RAMP command"
            )

        start_value = self.current_value
        self._to_u32_signed(start_value, "current_value")
        if step is None:
            step_value = self.calc_step(start_value, target, duration)
        else:
            self._to_step_field(step, "step")
            step_value = int(step)
        self.last_ramp_start = start_value
        self.last_ramp_step = step_value

        cmd = self.pack_cmd(target=target, start=0, duration=command_duration,
                            step=step_value, opcode=self.OP_RAMP,
                            hold_zero=hold_zero, clear=clear)
        self.current_value = target
        self.current_valid = True
        return cmd

    def idle_cmd(self, duration=0, clear=False):
        """Timed IDLE is unsupported by the current RTL."""
        raise NotImplementedError(
            "axis_awg_tuning_v1 no longer supports timed IDLE; "
            "schedule timing in the tProcessor program instead"
        )

    def reset_cache(self, value=0, valid=False):
        """Reset the software-side current-value cache."""
        value = self._check_int(value, "value")
        self._to_u32_signed(value, "value")
        self.current_value = value
        self.current_valid = bool(valid)
        self.last_ramp_start = None
        self.last_ramp_step = None

    def make_sequence(self, instructions):
        """Pack a list of instruction dictionaries into command words.

        Supported forms include ``{"op": "set", "value": ...}``,
        ``{"op": "ramp", "target": ..., "duration": ...}``, and
        ``{"op": "nop"}``. This only packs command words; it does not
        schedule tProcessor timing. Since commands during a ramp are dropped by
        hardware, user code must emit subsequent meaningful commands only after
        the active ramp has completed.
        """
        cmds = []
        for inst in instructions:
            op = inst.get("op")
            if op == "nop":
                cmds.append(self.nop_cmd(clear=inst.get("clear", False)))
            elif op == "set":
                cmds.append(self.set_cmd(
                    inst["value"],
                    hold_zero=inst.get("hold_zero", False),
                    clear=inst.get("clear", False),
                    saturate=inst.get("saturate", False),
                ))
            elif op == "ramp":
                if "start" in inst:
                    raise ValueError(
                        "start field is deprecated and ignored by the current RTL; "
                        "remove it from ramp instructions"
                    )
                cmds.append(self.ramp_cmd(
                    inst["target"],
                    inst["duration"],
                    step=inst.get("step", None),
                    hold_zero=inst.get("hold_zero", False),
                    clear=inst.get("clear", False),
                ))
            elif op == "idle":
                cmds.append(self.idle_cmd(inst.get("duration", 0), clear=inst.get("clear", False)))
            else:
                raise ValueError(f"unknown AWG tuning op {op!r}")
        return cmds

    def cmd_to_words(self, cmd):
        """Return five 32-bit words, least-significant word first."""
        cmd = self._check_int(cmd, "cmd")
        if cmd < 0 or cmd >= (1 << self["cmd_width"]):
            raise ValueError("cmd is outside the configured command width")
        return [(cmd >> (32 * i)) & 0xFFFFFFFF for i in range(5)]

    def format_cmd(self, cmd):
        """Decode a packed command into a readable dictionary.

        The RAMP start command field is reported as ignored because the current
        RTL starts from its internal current value. The RAMP step field is
        active and is used directly by RTL.
        """
        cmd = self._check_int(cmd, "cmd")
        if cmd < 0 or cmd >= (1 << self["cmd_width"]):
            raise ValueError("cmd is outside the configured command width")

        opcode = (cmd >> 144) & 0b11
        names = {
            self.OP_NOP: "nop",
            self.OP_SET: "set",
            self.OP_RAMP: "ramp",
            self.OP_IDLE: "idle",
        }
        reserved_start = self._from_u32_signed(cmd >> 32)
        duration = (cmd >> 64) & ((1 << self.DURATION_WIDTH) - 1)
        step = self._from_signed_field(cmd >> 96, self.STEP_WIDTH)
        return {
            "opcode": opcode,
            "op": names.get(opcode, "unknown"),
            "target": self._from_u32_signed(cmd),
            "reserved_start": reserved_start,
            "start_ignored": reserved_start,
            "duration": duration,
            "step": step,
            "duration_ignored_high": (cmd >> 87) & 0x1FF,
            "step_ignored_high": (cmd >> 120) & 0xFF,
            "hold_zero": bool((cmd >> 146) & 0x1),
            "clear": bool((cmd >> 148) & 0x1),
        }


@dataclass
class TimedCommandEvent:
    """A timed 160-bit command event emitted by software or a tProcessor model."""

    cycle: int
    word: int
    channel: Optional[int] = None
    tproc_ch: Optional[int] = None
    tmux_ch: Optional[int] = None
    label: Optional[str] = None
    source_cycle: Optional[int] = None
    route_latency: int = 0


@dataclass
class CommandEvent:
    """A decoded AWG command as seen by an AWG behavior model."""

    cycle: int
    channel: int
    raw_command: int
    decoded: Dict[str, Any]
    label: Optional[str] = None
    reason: Optional[str] = None
    output_cycle: Optional[int] = None


@dataclass
class TimingConflict:
    """A simulator-detected timing or routing conflict."""

    cycle: int
    channel: int
    description: str


@dataclass
class WaveformResult:
    """Output waveform and command log from the Python AWG behavior model.

    This is a behavioral/cycle-level software model for program validation. It
    is not a replacement for RTL simulation, implementation, or timing closure.
    For one AWG channel, ``packed_words`` has shape ``(cycles,)`` and
    ``lane_samples`` has shape ``(cycles, n_pts)``. For multiple channels, the
    arrays are shaped ``(cycles, channels)`` and ``(cycles, channels, n_pts)``.
    """

    packed_words: np.ndarray
    lane_samples: np.ndarray
    command_events: List[CommandEvent]
    accepted_commands: List[CommandEvent]
    dropped_commands: List[CommandEvent]
    timing_conflicts: List[TimingConflict]
    channels: Optional[List[int]] = None
    channel_results: Optional[Dict[int, "WaveformResult"]] = None
    unsupported_ips: List[str] = field(default_factory=list)
    unsupported_instructions: List[str] = field(default_factory=list)
    unsupported_modes: List[str] = field(default_factory=list)
    ip_events: List[Dict[str, Any]] = field(default_factory=list)

    def to_dict(self):
        """Return a JSON-like dictionary with arrays converted to lists."""
        return {
            "packed_words": self.packed_words.tolist(),
            "lane_samples": self.lane_samples.tolist(),
            "command_events": [event.__dict__.copy() for event in self.command_events],
            "accepted_commands": [event.__dict__.copy() for event in self.accepted_commands],
            "dropped_commands": [event.__dict__.copy() for event in self.dropped_commands],
            "timing_conflicts": [event.__dict__.copy() for event in self.timing_conflicts],
            "channels": None if self.channels is None else list(self.channels),
            "unsupported_ips": list(self.unsupported_ips),
            "unsupported_instructions": list(self.unsupported_instructions),
            "unsupported_modes": list(self.unsupported_modes),
            "ip_events": [dict(event) for event in self.ip_events],
        }

    def summary(self):
        """Return a compact count summary for tests and reports."""
        return {
            "cycles": int(np.asarray(self.packed_words).shape[0]) if self.packed_words is not None else 0,
            "commands": len(self.command_events),
            "accepted": len(self.accepted_commands),
            "dropped": len(self.dropped_commands),
            "timing_conflicts": len(self.timing_conflicts),
            "unsupported_ips": len(self.unsupported_ips),
            "unsupported_instructions": len(self.unsupported_instructions),
            "unsupported_modes": len(self.unsupported_modes),
            "ip_events": len(self.ip_events),
        }

    @staticmethod
    def _hex_word(word):
        return "0x%x" % int(word)

    def to_csv(self, prefix):
        """Write CSV files compatible with the AWG RTL simulation plot flow.

        Files written:
        ``<prefix>_awg_packed.csv``, ``<prefix>_awg_x16.csv``, and
        ``<prefix>_events.csv``. A multi-channel result adds a ``channel``
        column to disambiguate rows.
        """
        prefix = Path(prefix)
        packed_path = prefix.with_name(prefix.name + "_awg_packed.csv")
        x16_path = prefix.with_name(prefix.name + "_awg_x16.csv")
        events_path = prefix.with_name(prefix.name + "_events.csv")

        packed = np.asarray(self.packed_words, dtype=object)
        lanes = np.asarray(self.lane_samples)
        multi = packed.ndim == 2
        channels = self.channels or list(range(packed.shape[1] if multi else 1))

        with packed_path.open("w", newline="") as f:
            fields = ["cycle", "word_index", "tvalid", "tready", "tdata_hex"]
            if multi:
                fields.insert(1, "channel")
            writer = csv.DictWriter(f, fieldnames=fields)
            writer.writeheader()
            if multi:
                for cycle in range(packed.shape[0]):
                    for ch_idx, ch in enumerate(channels):
                        writer.writerow({
                            "cycle": cycle,
                            "channel": ch,
                            "word_index": cycle,
                            "tvalid": 1,
                            "tready": 1,
                            "tdata_hex": self._hex_word(packed[cycle, ch_idx]),
                        })
            else:
                for cycle, word in enumerate(packed):
                    writer.writerow({
                        "cycle": cycle,
                        "word_index": cycle,
                        "tvalid": 1,
                        "tready": 1,
                        "tdata_hex": self._hex_word(word),
                    })

        with x16_path.open("w", newline="") as f:
            fields = ["sample_index", "slow_word", "lane", "value"]
            if multi:
                fields.insert(1, "channel")
            writer = csv.DictWriter(f, fieldnames=fields)
            writer.writeheader()
            if multi:
                n_pts = lanes.shape[2]
                for cycle in range(lanes.shape[0]):
                    for ch_idx, ch in enumerate(channels):
                        for lane in range(n_pts):
                            writer.writerow({
                                "sample_index": cycle * n_pts + lane,
                                "channel": ch,
                                "slow_word": cycle,
                                "lane": lane,
                                "value": int(lanes[cycle, ch_idx, lane]),
                            })
            else:
                n_pts = lanes.shape[1]
                for cycle in range(lanes.shape[0]):
                    for lane in range(n_pts):
                        writer.writerow({
                            "sample_index": cycle * n_pts + lane,
                            "slow_word": cycle,
                            "lane": lane,
                            "value": int(lanes[cycle, lane]),
                        })

        with events_path.open("w", newline="") as f:
            fields = ["path", "label", "setting_cycle", "output_cycle", "delay_cycles", "detail"]
            writer = csv.DictWriter(f, fieldnames=fields)
            writer.writeheader()
            for event in self.command_events:
                setting_cycle = event.decoded.get("source_cycle", event.cycle)
                output_cycle = event.output_cycle
                if output_cycle is None:
                    output_cycle = event.cycle
                writer.writerow({
                    "path": "awg%d" % event.channel,
                    "label": event.label or event.decoded.get("op", "cmd"),
                    "setting_cycle": setting_cycle,
                    "output_cycle": output_cycle,
                    "delay_cycles": output_cycle - setting_cycle,
                    "detail": event.reason or event.decoded.get("op", "cmd"),
                })

        return {
            "packed": packed_path,
            "x16": x16_path,
            "events": events_path,
        }

    def plot(self, path=None, channel=None, lanes=None):
        """Plot lane samples if matplotlib is available.

        This helper is optional and is intentionally not required by tests.
        """
        try:
            import matplotlib.pyplot as plt
        except ImportError as exc:
            raise RuntimeError("matplotlib is required for WaveformResult.plot()") from exc

        arr = np.asarray(self.lane_samples)
        if arr.ndim == 3:
            channels = self.channels or list(range(arr.shape[1]))
            if channel is None:
                channel = channels[0]
            ch_idx = channels.index(channel)
            arr = arr[:, ch_idx, :]

        if lanes is None:
            lanes = range(arr.shape[1])

        fig, ax = plt.subplots(figsize=(10, 4))
        cycles = np.arange(arr.shape[0])
        for lane in lanes:
            ax.step(cycles, arr[:, lane], where="post", label="lane %d" % lane)
        ax.set_xlabel("AWG fabric cycle")
        ax.set_ylabel("sample")
        ax.grid(True, alpha=0.3)
        ax.legend(loc="best")
        fig.tight_layout()
        if path is not None:
            fig.savefig(path, dpi=150)
        return fig, ax


class AwgTuningBehaviorModel:
    """Cycle-level Python model of ``axis_awg_tuning_v1`` command behavior.

    The model follows the current RTL command semantics: SET is visible in the
    command cycle, RAMP starts from the internal current value, RAMP output
    begins after ``extra_y_pipe_stages + 4`` cycles, and commands delivered
    while RAMP_ST is active are recorded as dropped. It models waveform timing
    and sample rules, not RTL implementation details or timing closure.
    """

    OP_NOP = AxisAwgTuningV1.OP_NOP
    OP_SET = AxisAwgTuningV1.OP_SET
    OP_RAMP = AxisAwgTuningV1.OP_RAMP
    OP_IDLE = AxisAwgTuningV1.OP_IDLE

    def __init__(
        self,
        n_pts=16,
        b=16,
        frac=16,
        cmd_width=160,
        step_width=24,
        duration_width=23,
        extra_y_pipe_stages=3,
        initial_value=0,
        channel=0,
    ):
        self.n_pts = int(n_pts)
        self.b = int(b)
        self.frac = int(frac)
        self.cmd_width = int(cmd_width)
        self.step_width = int(step_width)
        self.duration_width = int(duration_width)
        self.extra_y_pipe_stages = int(extra_y_pipe_stages)
        self.ramp_startup_latency_cycles = self.extra_y_pipe_stages + 4
        self.channel = int(channel)

        self.dac_invalid_lsb = self.b - AxisAwgTuningV1.DAC_EFFECTIVE_BITS
        if self.dac_invalid_lsb < 0:
            raise ValueError("DAC effective bits cannot exceed output word bits")
        self._lane_mask = (1 << self.b) - 1
        self._duration_mask = (1 << self.duration_width) - 1
        self._step_mask = (1 << self.step_width) - 1
        self.maxv = ((1 << (self.b - 1)) - 1) & ~((1 << self.dac_invalid_lsb) - 1)
        self.minv = -(1 << (self.b - 1))

        self.initial_value = self._check_int(initial_value, "initial_value")
        self.reset(self.initial_value)

    @staticmethod
    def _check_int(value, name):
        if isinstance(value, (bool, np.bool_)) or not isinstance(value, (int, np.integer)):
            raise ValueError("%s must be an integer" % name)
        return int(value)

    @staticmethod
    def _sign_extend(value, width):
        mask = (1 << width) - 1
        sign = 1 << (width - 1)
        value = int(value) & mask
        if value & sign:
            return value - (1 << width)
        return value

    @staticmethod
    def _div_trunc_zero(num, den):
        return AxisAwgTuningV1._div_trunc_zero(num, den)

    def reset(self, initial_value=0):
        """Reset model state to IDLE and clear event logs."""
        self.state = "idle"
        self.current_value = self._check_int(initial_value, "initial_value")
        self.hold_sample = self.clip_sample(self.current_value)
        self._output_overrides = {}
        self._ramp_outputs = {}
        self._ramp_busy_until = None
        self._ramp_target = self.current_value
        self.command_events = []
        self.accepted_commands = []
        self.dropped_commands = []
        self.timing_conflicts = []

    def clip_sample(self, value):
        """Clip and 14-bit-align a signed scalar sample."""
        value = self._check_int(value, "value")
        value = max(self.minv, min(self.maxv, value))
        if self.dac_invalid_lsb:
            value &= ~((1 << self.dac_invalid_lsb) - 1)
        return int(value)

    def clip_fixed_sample(self, fixed_value):
        """Arithmetic-shift a fixed-point value and clip it to a DAC lane."""
        return self.clip_sample(int(fixed_value) >> self.frac)

    def normalize_duration(self, duration):
        duration = int(duration) & self._duration_mask
        return 1 if duration == 0 else duration

    def pack_lanes(self, samples):
        """Pack signed lane samples into a little-lane-endian AWG output word."""
        word = 0
        for lane, sample in enumerate(samples):
            word |= (int(sample) & self._lane_mask) << (lane * self.b)
        return word

    def unpack_lanes(self, word, n_pts=None):
        """Extract signed lane samples from a packed AWG output word."""
        if n_pts is None:
            n_pts = self.n_pts
        samples = []
        for lane in range(int(n_pts)):
            sample = (int(word) >> (lane * self.b)) & self._lane_mask
            samples.append(self._sign_extend(sample, self.b))
        return samples

    def scalar_word(self, value):
        """Return one output word with the clipped scalar replicated on all lanes."""
        sample = self.clip_sample(value)
        return self.pack_lanes([sample] * self.n_pts)

    def decode_command(self, cmd):
        """Decode the 160-bit command format used by the AWG tuning RTL."""
        cmd = self._check_int(cmd, "cmd")
        if cmd < 0 or cmd >= (1 << self.cmd_width):
            raise ValueError("cmd is outside the configured command width")
        opcode = (cmd >> 144) & 0b11
        names = {
            self.OP_NOP: "nop",
            self.OP_SET: "set",
            self.OP_RAMP: "ramp",
            self.OP_IDLE: "idle",
        }
        return {
            "opcode": opcode,
            "op": names.get(opcode, "unknown"),
            "target": self._sign_extend(cmd, 32),
            "reserved_start": self._sign_extend(cmd >> 32, 32),
            "start_ignored": self._sign_extend(cmd >> 32, 32),
            "duration": (cmd >> 64) & self._duration_mask,
            "step": self._sign_extend(cmd >> 96, self.step_width),
            "duration_ignored_high": (cmd >> 87) & 0x1FF,
            "step_ignored_high": (cmd >> 120) & 0xFF,
            "opcode_reserved_high": (cmd >> 149) & ((1 << max(0, self.cmd_width - 149)) - 1),
            "tmux_select": (cmd >> 152) & 0xFF if self.cmd_width >= 160 else 0,
            "hold_zero": bool((cmd >> 146) & 0x1),
            "clear": bool((cmd >> 148) & 0x1),
        }

    def calc_step(self, start, target, duration):
        """Calculate a signed fixed-point RAMP step using truncation to zero."""
        start = self._check_int(start, "start")
        target = self._check_int(target, "target")
        duration = int(duration) & self._duration_mask
        if duration <= 1:
            return 0
        return self._div_trunc_zero((target - start) << self.frac, duration - 1)

    def expected_ramp_word(self, start, target, duration, step, base_index):
        """Return the RAMP output word for ``base_index`` using RTL formulas."""
        duration = self.normalize_duration(duration)
        samples = []
        for lane in range(self.n_pts):
            sample_index = int(base_index) + lane
            if duration <= 1 or sample_index >= duration - 1:
                samples.append(self.clip_sample(target))
            else:
                fixed_value = (int(start) << self.frac) + sample_index * int(step)
                samples.append(self.clip_fixed_sample(fixed_value))
        return self.pack_lanes(samples)

    def _finish_ramp(self):
        self.state = "idle"
        self.current_value = self._ramp_target
        self.hold_sample = self.clip_sample(self._ramp_target)
        self._ramp_busy_until = None

    def _retire_if_past_ramp(self, cycle):
        if self.state == "ramp" and self._ramp_busy_until is not None and cycle > self._ramp_busy_until:
            self._finish_ramp()

    def is_ramping_at(self, cycle):
        self._retire_if_past_ramp(cycle)
        return self.state == "ramp" and self._ramp_busy_until is not None and cycle <= self._ramp_busy_until

    def accept_command(self, cycle, cmd, label=None):
        """Deliver one command to the model at ``cycle``.

        Accepted and dropped commands are logged. A command delivered during
        RAMP_ST is not applied and is recorded with reason
        ``"dropped_during_ramp"``.
        """
        cycle = int(cycle)
        decoded = self.decode_command(cmd)
        event = CommandEvent(
            cycle=cycle,
            channel=self.channel,
            raw_command=int(cmd),
            decoded=decoded.copy(),
            label=label,
        )
        self.command_events.append(event)

        if self.is_ramping_at(cycle):
            event.reason = "dropped_during_ramp"
            self.dropped_commands.append(event)
            return event

        op = decoded["op"]
        if op == "set":
            target = decoded["target"]
            self._output_overrides[cycle] = self.scalar_word(target)
            self.current_value = 0 if decoded["hold_zero"] else target
            self.hold_sample = 0 if decoded["hold_zero"] else self.clip_sample(target)
            event.output_cycle = cycle
            self.accepted_commands.append(event)
        elif op == "ramp":
            duration = self.normalize_duration(decoded["duration"])
            start = self.current_value
            target = decoded["target"]
            step = decoded["step"]
            n_words = max(1, (duration + self.n_pts - 1) // self.n_pts)
            first_cycle = cycle + self.ramp_startup_latency_cycles
            for word_idx in range(n_words):
                base_index = word_idx * self.n_pts
                self._ramp_outputs[first_cycle + word_idx] = self.expected_ramp_word(
                    start, target, duration, step, base_index
                )
            self.state = "ramp"
            self._ramp_target = target
            self._ramp_busy_until = first_cycle + n_words - 1
            event.decoded["effective_duration"] = duration
            event.decoded["start_value"] = start
            event.decoded["n_output_words"] = n_words
            event.output_cycle = first_cycle
            self.accepted_commands.append(event)
        else:
            event.output_cycle = cycle
            self.accepted_commands.append(event)
        return event

    def step(self, cycle):
        """Return the packed output word visible at ``cycle``."""
        cycle = int(cycle)
        self._retire_if_past_ramp(cycle)
        if cycle in self._output_overrides:
            word = self._output_overrides[cycle]
        elif cycle in self._ramp_outputs:
            word = self._ramp_outputs[cycle]
        else:
            word = self.pack_lanes([self.hold_sample] * self.n_pts)

        if self.state == "ramp" and self._ramp_busy_until == cycle:
            self._finish_ramp()
        return word

    def run(self, cycles, events=None):
        """Run the model for ``cycles`` fabric clock cycles."""
        events = [] if events is None else list(events)
        by_cycle = {}
        for event in events:
            by_cycle.setdefault(int(event.cycle), []).append(event)

        packed = []
        lanes = []
        for cycle in range(int(cycles)):
            cycle_events = by_cycle.get(cycle, [])
            if len(cycle_events) > 1:
                self.timing_conflicts.append(TimingConflict(
                    cycle=cycle,
                    channel=self.channel,
                    description="multiple commands delivered to one AWG in one cycle",
                ))
            for event in cycle_events:
                self.accept_command(cycle, event.word, event.label)
            word = self.step(cycle)
            packed.append(word)
            lanes.append(self.unpack_lanes(word))

        return WaveformResult(
            packed_words=np.array(packed, dtype=object),
            lane_samples=np.array(lanes, dtype=np.int64),
            command_events=list(self.command_events),
            accepted_commands=list(self.accepted_commands),
            dropped_commands=list(self.dropped_commands),
            timing_conflicts=list(self.timing_conflicts),
            channels=[self.channel],
        )


class TProcTimedEventSimulator:
    """Route timed tProcessor-like command events into AWG behavior models.

    Explicit events are supported directly. A limited ``from_program`` helper
    can inspect already-expanded ASM v1 ``prog_list`` instructions for the
    ``regwi``/``bitwi``/``mathi``/``set`` subset used by the AWG tuning
    manager. This is not a full tProcessor ISA simulator.
    """

    def __init__(
        self,
        models=None,
        num_channels=1,
        events=None,
        use_tmux=False,
        tmux_latency=2,
        **model_kwargs
    ):
        if models is None:
            self.models = {
                ch: AwgTuningBehaviorModel(channel=ch, **model_kwargs)
                for ch in range(int(num_channels))
            }
        else:
            self.models = dict(models)
        self.events = [] if events is None else list(events)
        self.use_tmux = bool(use_tmux)
        self.tmux_latency = int(tmux_latency)
        self.timing_conflicts = []
        self.routed_events = []

    @staticmethod
    def _words_to_cmd(words):
        cmd = 0
        for idx, word in enumerate(words):
            cmd |= (int(word) & 0xFFFFFFFF) << (32 * idx)
        return cmd

    @staticmethod
    def _inst_name_args(inst):
        if isinstance(inst, dict):
            return inst.get("name") or inst.get("op"), inst.get("args", ())
        if isinstance(inst, (tuple, list)) and inst:
            return inst[0], tuple(inst[1:])
        name = getattr(inst, "name", None) or getattr(inst, "op", None)
        args = getattr(inst, "args", ())
        return name, args

    @classmethod
    def _events_from_prog_list(cls, prog_list, use_tmux=True, default_channel=0):
        regs = {}
        events = []

        def get_reg(page, reg):
            return regs.get((int(page), int(reg)), 0)

        for inst in prog_list:
            name, args = cls._inst_name_args(inst)
            if name is None:
                continue
            name = str(name).lower()
            args = tuple(args)

            if name == "regwi" and len(args) >= 3:
                page, reg, imm = args[:3]
                regs[(int(page), int(reg))] = int(imm) & 0xFFFFFFFF
            elif name == "bitwi" and len(args) >= 5:
                page, dst, src, op, imm = args[:5]
                src_value = get_reg(page, src)
                imm = int(imm)
                if op == "<<":
                    value = src_value << imm
                elif op == ">>":
                    value = src_value >> imm
                elif op == "&":
                    value = src_value & imm
                elif op == "|":
                    value = src_value | imm
                else:
                    continue
                regs[(int(page), int(dst))] = value & 0xFFFFFFFF
            elif name == "mathi" and len(args) >= 5:
                page, dst, src, op, imm = args[:5]
                src_value = get_reg(page, src)
                imm = int(imm)
                if op == "+":
                    value = src_value + imm
                elif op == "-":
                    value = src_value - imm
                elif op == "*":
                    value = src_value * imm
                else:
                    continue
                regs[(int(page), int(dst))] = value & 0xFFFFFFFF
            elif name == "set" and len(args) >= 8:
                tproc_ch, page, r0, r1, r2, r3, r4, rt = args[:8]
                words = [get_reg(page, reg) for reg in (r0, r1, r2, r3, r4)]
                cmd = cls._words_to_cmd(words)
                tmux_ch = ((cmd >> 152) & 0xFF) if use_tmux else None
                channel = None if use_tmux else default_channel
                events.append(TimedCommandEvent(
                    cycle=get_reg(page, rt),
                    word=cmd,
                    channel=channel,
                    tproc_ch=int(tproc_ch),
                    tmux_ch=tmux_ch,
                    label="prog_set",
                    source_cycle=get_reg(page, rt),
                    route_latency=0,
                ))
        return events

    @classmethod
    def from_program(cls, prog, soccfg=None, cycles=None, use_tmux=True, **model_kwargs):
        """Create a simulator from an expanded ASM v1 program object.

        This runs the Python tProcessor v1 behavior model and consumes its
        timed output events. The interpreter covers the instruction names
        declared by ASM v1 and records unsupported instructions in strict mode.
        If ``cycles`` is supplied it is stored as ``default_cycles``.
        """
        prog_list = getattr(prog, "prog_list", None)
        if prog_list is None:
            prog_list = getattr(prog, "program", None)
        if prog_list is None:
            raise ValueError("program object does not expose prog_list/program instructions")

        num_channels = len(soccfg.get("gens", [])) if soccfg is not None else model_kwargs.pop("num_channels", 1)
        tproc = TProcV1BehaviorModel(strict=model_kwargs.pop("strict_tproc", True))
        tproc.run(prog_list)
        events = tproc.output_events
        sim = cls(num_channels=num_channels, events=events, use_tmux=use_tmux, **model_kwargs)
        sim.tproc_result = tproc
        sim.default_cycles = cycles
        return sim

    @classmethod
    def from_awg_pulses(cls, events, **kwargs):
        """Create a simulator from explicit AWG command events."""
        return cls(events=list(events), **kwargs)

    def _route_events(self, events):
        delivered = []
        seen = {}
        self.routed_events = []
        for event in events:
            word = int(event.word)
            route_tmux = self.use_tmux or event.tmux_ch is not None
            cycle = int(event.cycle)
            if route_tmux:
                if event.tmux_ch is not None:
                    word |= (int(event.tmux_ch) & 0xFF) << 152
                tmux_select = (word >> 152) & 0xFF
                channel = tmux_select & 0x7
                out_cycle = cycle + self.tmux_latency
                if event.channel is not None and int(event.channel) != channel:
                    self.timing_conflicts.append(TimingConflict(
                        cycle=cycle,
                        channel=int(event.channel),
                        description="TMUX select routes command to channel %d" % channel,
                    ))
                routed = TimedCommandEvent(
                    cycle=out_cycle,
                    word=word,
                    channel=channel,
                    tproc_ch=event.tproc_ch,
                    tmux_ch=tmux_select,
                    label=event.label,
                    source_cycle=cycle,
                    route_latency=self.tmux_latency,
                )
            else:
                channel = 0 if event.channel is None else int(event.channel)
                routed = TimedCommandEvent(
                    cycle=cycle,
                    word=word,
                    channel=channel,
                    tproc_ch=event.tproc_ch,
                    tmux_ch=None,
                    label=event.label,
                    source_cycle=event.source_cycle if event.source_cycle is not None else cycle,
                    route_latency=0,
                )

            key = (routed.cycle, routed.channel)
            if key in seen:
                self.timing_conflicts.append(TimingConflict(
                    cycle=routed.cycle,
                    channel=routed.channel,
                    description="multiple routed commands target one AWG in one cycle",
                ))
            seen[key] = True
            self.routed_events.append(routed)
            if routed.channel in self.models:
                delivered.append(routed)
            else:
                self.timing_conflicts.append(TimingConflict(
                    cycle=routed.cycle,
                    channel=routed.channel,
                    description="no AWG behavior model for routed channel",
                ))
        return delivered

    def run(self, cycles=None, events=None):
        """Run all AWG channel models over a common cycle range."""
        events = list(self.events if events is None else events)
        delivered = self._route_events(events)
        if cycles is None:
            cycles = getattr(self, "default_cycles", None)
        if cycles is None:
            max_event_cycle = max([event.cycle for event in delivered], default=0)
            max_busy = max(
                [model.ramp_startup_latency_cycles + 8 for model in self.models.values()],
                default=16,
            )
            cycles = max_event_cycle + max_busy + 16
        cycles = int(cycles)

        by_cycle = {}
        for event in delivered:
            by_cycle.setdefault(int(event.cycle), []).append(event)

        channels = sorted(self.models)
        packed = {ch: [] for ch in channels}
        lanes = {ch: [] for ch in channels}
        for cycle in range(cycles):
            for event in by_cycle.get(cycle, []):
                accepted = self.models[event.channel].accept_command(cycle, event.word, event.label)
                accepted.decoded["source_cycle"] = event.source_cycle if event.source_cycle is not None else cycle
                accepted.decoded["route_latency"] = int(event.route_latency)
            for ch in channels:
                word = self.models[ch].step(cycle)
                packed[ch].append(word)
                lanes[ch].append(self.models[ch].unpack_lanes(word))

        channel_results = {}
        all_commands = []
        all_accepted = []
        all_dropped = []
        all_conflicts = list(self.timing_conflicts)
        for ch in channels:
            model = self.models[ch]
            channel_results[ch] = WaveformResult(
                packed_words=np.array(packed[ch], dtype=object),
                lane_samples=np.array(lanes[ch], dtype=np.int64),
                command_events=list(model.command_events),
                accepted_commands=list(model.accepted_commands),
                dropped_commands=list(model.dropped_commands),
                timing_conflicts=list(model.timing_conflicts),
                channels=[ch],
            )
            all_commands.extend(model.command_events)
            all_accepted.extend(model.accepted_commands)
            all_dropped.extend(model.dropped_commands)
            all_conflicts.extend(model.timing_conflicts)

        if len(channels) == 1:
            ch = channels[0]
            return WaveformResult(
                packed_words=np.array(packed[ch], dtype=object),
                lane_samples=np.array(lanes[ch], dtype=np.int64),
                command_events=all_commands,
                accepted_commands=all_accepted,
                dropped_commands=all_dropped,
                timing_conflicts=all_conflicts,
                channels=channels,
                channel_results=channel_results,
            )

        packed_arr = np.array([[packed[ch][cycle] for ch in channels] for cycle in range(cycles)], dtype=object)
        lanes_arr = np.array([[lanes[ch][cycle] for ch in channels] for cycle in range(cycles)], dtype=np.int64)
        return WaveformResult(
            packed_words=packed_arr,
            lane_samples=lanes_arr,
            command_events=all_commands,
            accepted_commands=all_accepted,
            dropped_commands=all_dropped,
            timing_conflicts=all_conflicts,
            channels=channels,
            channel_results=channel_results,
        )


class UnsupportedIPError(RuntimeError):
    """Raised when a project IP is not modeled in strict simulation mode."""


class UnsupportedInstructionError(NotImplementedError):
    """Raised when a tProcessor instruction has no behavior-model handler."""


class UnsupportedModeError(RuntimeError):
    """Raised when a modeled IP receives an unsupported command mode."""


@dataclass
class IpEvent:
    """A routed packet or behavioral IP-side event."""

    cycle: int
    path: str
    event: str
    detail: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self):
        return {
            "cycle": self.cycle,
            "path": self.path,
            "event": self.event,
            "detail": dict(self.detail),
        }


class TProcV1BehaviorModel:
    """Behavioral interpreter for ASM v1 ``QickProgram.instructions``.

    This is a timing/event interpreter for Python-side program validation. It
    tracks register pages, register 0 as hardwired zero, a small data memory,
    labels/PC, stack, timed output queues, and tProcessor output events. It is
    not a binary tProc RTL model.
    """

    DECLARED_INSTRUCTIONS = [
        "pushi", "popi", "mathi", "seti", "synci", "waiti", "bitwi",
        "memri", "memwi", "regwi", "setbi", "loopnz", "end", "condj",
        "math", "set", "sync", "read", "wait", "bitw", "memr", "memw",
        "setb", "comment",
    ]

    def __init__(self, queue_depth=16, strict=True, input_queues=None):
        self.queue_depth = int(queue_depth)
        self.strict = bool(strict)
        self.input_queues = {} if input_queues is None else {
            int(k): list(v) for k, v in input_queues.items()
        }
        self.reset()

    @staticmethod
    def _u32(value):
        return int(value) & 0xFFFFFFFF

    @staticmethod
    def _s32(value):
        value = int(value) & 0xFFFFFFFF
        return value - 0x100000000 if value & 0x80000000 else value

    @staticmethod
    def _inst_name_args(inst):
        if isinstance(inst, dict):
            return inst.get("name") or inst.get("op"), tuple(inst.get("args", ()))
        if isinstance(inst, (tuple, list)) and inst:
            return inst[0], tuple(inst[1:])
        return getattr(inst, "name", None), tuple(getattr(inst, "args", ()))

    @classmethod
    def handler_names(cls):
        return {name[6:] for name in dir(cls) if name.startswith("_exec_")}

    @classmethod
    def missing_instruction_handlers(cls, instruction_names=None):
        if instruction_names is None:
            instruction_names = cls.DECLARED_INSTRUCTIONS
        return sorted(set(instruction_names) - cls.handler_names())

    def reset(self):
        self.pc = 0
        self.current_cycle = 0
        self.ended = False
        self.regs = {}
        self.dmem = {}
        self.stack = []
        self.labels = {}
        self.output_events = []
        self.output_pin_events = []
        self.timing_conflicts = []
        self.unsupported_instructions = []
        self.ip_events = []
        self._queue_counts = {}

    def _read_raw(self, page, reg):
        reg = int(reg)
        if reg == 0:
            return 0
        return self.regs.get((int(page), reg), 0) & 0xFFFFFFFF

    def _read_signed(self, page, reg):
        return self._s32(self._read_raw(page, reg))

    def _write_reg(self, page, reg, value):
        reg = int(reg)
        if reg == 0:
            return
        self.regs[(int(page), reg)] = self._u32(value)

    def _resolve_target(self, target):
        if isinstance(target, str):
            if target not in self.labels:
                raise ValueError("unknown program label %r" % target)
            return self.labels[target]
        return int(target)

    def _apply_math(self, a, op, b):
        if op == "+":
            return a + b
        if op == "-":
            return a - b
        if op == "*":
            return a * b
        if op == ">":
            return int(a > b)
        if op == ">=":
            return int(a >= b)
        if op == "<":
            return int(a < b)
        if op == "<=":
            return int(a <= b)
        if op == "==":
            return int(a == b)
        if op == "!=":
            return int(a != b)
        raise UnsupportedModeError("unsupported math operator %r" % (op,))

    def _apply_bit(self, a, op, b=0):
        a = self._u32(a)
        b = self._u32(b)
        if op == "&":
            return a & b
        if op == "|":
            return a | b
        if op == "^":
            return a ^ b
        if op == "~":
            return ~a
        if op == "<<":
            return a << int(b)
        if op == ">>":
            return a >> int(b)
        if op == "upper":
            return (a >> 16) & 0xFFFF
        if op == "lower":
            return a & 0xFFFF
        raise UnsupportedModeError("unsupported bit operator %r" % (op,))

    def _queue_output(self, port, cycle, word, label=None, kind="axis"):
        port = int(port)
        cycle = int(cycle)
        key = (port, cycle)
        count = self._queue_counts.get(key, 0)
        if count >= self.queue_depth:
            conflict = TimingConflict(
                cycle=cycle,
                channel=port,
                description="tProcessor output queue overflow on port %d" % port,
            )
            self.timing_conflicts.append(conflict)
            if self.strict:
                raise RuntimeError(conflict.description)
        if count > 0:
            conflict = TimingConflict(
                cycle=cycle,
                channel=port,
                description="multiple tProcessor writes scheduled to one port/cycle",
            )
            self.timing_conflicts.append(conflict)
            if self.strict:
                raise RuntimeError(conflict.description)
        self._queue_counts[key] = count + 1

        if kind == "axis":
            self.output_events.append(TimedCommandEvent(
                cycle=cycle,
                word=int(word),
                tproc_ch=port,
                label=label,
                source_cycle=cycle,
            ))
        else:
            self.output_pin_events.append({
                "cycle": cycle,
                "port": port,
                "word": int(word) & 0xFFFFFFFF,
                "label": label,
                "kind": kind,
            })

    def load_program(self, program):
        self.program = list(getattr(program, "prog_list", program))
        self.labels = {}
        for idx, inst in enumerate(self.program):
            if isinstance(inst, dict) and "label" in inst:
                self.labels[inst["label"]] = idx

    def run(self, program=None, max_steps=100000):
        if program is not None:
            self.load_program(program)
        if not hasattr(self, "program"):
            self.program = []
        steps = 0
        while not self.ended and 0 <= self.pc < len(self.program):
            if steps >= max_steps:
                raise RuntimeError("tProcessor simulator exceeded max_steps=%d" % max_steps)
            inst = self.program[self.pc]
            name, args = self._inst_name_args(inst)
            if name is None:
                self.pc += 1
                steps += 1
                continue
            name = str(name)
            handler = getattr(self, "_exec_" + name, None)
            if handler is None:
                self.unsupported_instructions.append(name)
                if self.strict:
                    raise UnsupportedInstructionError("unsupported tProc v1 instruction %s" % name)
                self.pc += 1
            else:
                handler(*args)
            steps += 1
        return self

    def _exec_comment(self, *args):
        self.pc += 1

    def _exec_end(self):
        self.ended = True
        self.pc += 1

    def _exec_regwi(self, page, reg, imm):
        self._write_reg(page, reg, imm)
        self.pc += 1

    def _exec_mathi(self, page, dst, src, op, imm):
        self._write_reg(page, dst, self._apply_math(self._read_signed(page, src), op, int(imm)))
        self.pc += 1

    def _exec_math(self, page, dst, src_a, op, src_b):
        self._write_reg(page, dst, self._apply_math(
            self._read_signed(page, src_a), op, self._read_signed(page, src_b)
        ))
        self.pc += 1

    def _exec_bitwi(self, page, dst, src, op, imm):
        self._write_reg(page, dst, self._apply_bit(self._read_raw(page, src), op, int(imm)))
        self.pc += 1

    def _exec_bitw(self, page, dst, src_a, op, src_b):
        self._write_reg(page, dst, self._apply_bit(
            self._read_raw(page, src_a), op, self._read_raw(page, src_b)
        ))
        self.pc += 1

    def _exec_memwi(self, page, reg, addr):
        self.dmem[int(addr)] = self._read_raw(page, reg)
        self.pc += 1

    def _exec_memri(self, page, reg, addr):
        self._write_reg(page, reg, self.dmem.get(int(addr), 0))
        self.pc += 1

    def _exec_memw(self, page, reg, addr_reg):
        self.dmem[self._read_raw(page, addr_reg)] = self._read_raw(page, reg)
        self.pc += 1

    def _exec_memr(self, page, dst, addr_reg):
        self._write_reg(page, dst, self.dmem.get(self._read_raw(page, addr_reg), 0))
        self.pc += 1

    def _exec_pushi(self, page, reg, op, imm):
        value = self._read_signed(page, reg)
        if op is not None:
            value = self._apply_math(value, op, int(imm))
        self.stack.append(self._u32(value))
        self.pc += 1

    def _exec_popi(self, page, reg):
        if not self.stack:
            raise RuntimeError("tProcessor stack underflow")
        self._write_reg(page, reg, self.stack.pop())
        self.pc += 1

    def _exec_loopnz(self, page, reg, target):
        value = self._read_signed(page, reg)
        if value != 0:
            self._write_reg(page, reg, value - 1)
            self.pc = self._resolve_target(target)
        else:
            self.pc += 1

    def _exec_condj(self, page, reg_a, op, reg_b, target):
        take = bool(self._apply_math(self._read_signed(page, reg_a), op, self._read_signed(page, reg_b)))
        self.pc = self._resolve_target(target) if take else self.pc + 1

    def _exec_synci(self, imm):
        self.current_cycle += int(imm)
        self.pc += 1

    def _exec_sync(self, page, reg):
        self.current_cycle = max(self.current_cycle, self._read_signed(page, reg))
        self.pc += 1

    def _exec_waiti(self, port, imm):
        self.current_cycle = max(self.current_cycle, int(imm))
        self.pc += 1

    def _exec_wait(self, page, port, reg):
        self.current_cycle = max(self.current_cycle, self._read_signed(page, reg))
        self.pc += 1

    def _exec_set(self, port, page, r0, r1, r2, r3, r4, rt):
        words = [self._read_raw(page, reg) for reg in (r0, r1, r2, r3, r4)]
        cycle = self.current_cycle + self._read_raw(page, rt)
        word = TProcTimedEventSimulator._words_to_cmd(words)
        self._queue_output(port, cycle, word, kind="axis")
        self.pc += 1

    def _exec_seti(self, port, page, reg, time_imm):
        self._queue_output(port, self.current_cycle + int(time_imm), self._read_raw(page, reg), kind="pin")
        self.pc += 1

    def _exec_setb(self, page, reg, time_reg):
        self._queue_output(0, self.current_cycle + self._read_raw(page, time_reg), self._read_raw(page, reg), kind="pin")
        self.pc += 1

    def _exec_setbi(self, page, reg, time_imm):
        self._queue_output(0, self.current_cycle + int(time_imm), self._read_raw(page, reg), kind="pin")
        self.pc += 1

    def _exec_read(self, page, port, op, dst):
        queue = self.input_queues.setdefault(int(port), [])
        value = queue.pop(0) if queue else 0
        if op in (None, "lower"):
            out = value
        elif op == "upper":
            out = int(value) >> 32
        else:
            out = value
        self._write_reg(page, dst, out)
        self.pc += 1


class AxisTmuxV1BehaviorModel:
    """Behavioral model of ``axis_tmux_v1`` upper-byte routing."""

    def __init__(self, latency=2, outputs=8):
        self.latency = int(latency)
        self.outputs = int(outputs)

    def route(self, event):
        word = int(event.word)
        select = (word >> 152) & 0xFF
        channel = select & 0x7
        return TimedCommandEvent(
            cycle=int(event.cycle) + self.latency,
            word=word,
            channel=channel,
            tproc_ch=event.tproc_ch,
            tmux_ch=select,
            label=event.label,
            source_cycle=event.source_cycle if event.source_cycle is not None else event.cycle,
            route_latency=int(event.route_latency) + self.latency,
        )


class AxisRegisterSliceBehaviorModel:
    """Simple AXIS register-slice model with configurable latency."""

    def __init__(self, latency=1, name="axis_register_slice"):
        self.latency = int(latency)
        self.name = name

    def route(self, event):
        event = TimedCommandEvent(**event.__dict__)
        event.cycle += self.latency
        event.route_latency += self.latency
        return event


class AxisClockConverterBehaviorModel(AxisRegisterSliceBehaviorModel):
    """Clock converter model. Clocks are treated as synchronous by default."""

    def __init__(self, latency=0, name="axis_clock_converter"):
        super().__init__(latency=latency, name=name)


class AxisBroadcasterBehaviorModel:
    """Duplicate one AXIS event to multiple outputs."""

    def __init__(self, outputs=2, latency=0):
        self.outputs = int(outputs)
        self.latency = int(latency)

    def route(self, event):
        routed = []
        for channel in range(self.outputs):
            routed.append(TimedCommandEvent(
                cycle=int(event.cycle) + self.latency,
                word=int(event.word),
                channel=channel,
                tproc_ch=event.tproc_ch,
                tmux_ch=event.tmux_ch,
                label=event.label,
                source_cycle=event.source_cycle,
                route_latency=int(event.route_latency) + self.latency,
            ))
        return routed


class AxisSwitchBehaviorModel:
    """Behavioral AXIS switch model using a selected input/output map."""

    def __init__(self, selection=None, latency=0, strict=True):
        self.selection = {} if selection is None else dict(selection)
        self.latency = int(latency)
        self.strict = bool(strict)

    def route(self, event, input_port=0):
        if input_port not in self.selection:
            if self.strict:
                raise UnsupportedModeError("axis_switch input %s is not selected" % input_port)
            return None
        event = TimedCommandEvent(**event.__dict__)
        event.channel = self.selection[input_port]
        event.cycle += self.latency
        event.route_latency += self.latency
        return event


class RfdcDacSinkModel:
    """Collect packed DAC words and lane samples from a model output."""

    def __init__(self, name, n_lanes=16, b=16):
        self.name = name
        self.n_lanes = int(n_lanes)
        self.b = int(b)
        self.words = []

    def write(self, cycle, word):
        model = AwgTuningBehaviorModel(n_pts=self.n_lanes, b=self.b)
        self.words.append({
            "cycle": int(cycle),
            "word": int(word),
            "lanes": model.unpack_lanes(word),
        })


class RfdcAdcSourceModel:
    """Configurable ADC source for readout and buffer behavior tests."""

    def __init__(self, samples=None, n_lanes=8):
        self.samples = [] if samples is None else list(samples)
        self.n_lanes = int(n_lanes)
        self.index = 0

    def read_word(self):
        if self.index < len(self.samples):
            value = self.samples[self.index]
            self.index += 1
            return value
        return [0] * self.n_lanes


class AxisSignalGenV6BehaviorModel:
    """Behavioral model for ``axis_signal_gen_v6`` command timing and DDS mode."""

    def __init__(self, n_dds=16, b=16, strict=True, latency=0, name="axis_signal_gen_v6"):
        self.n_dds = int(n_dds)
        self.b = int(b)
        self.strict = bool(strict)
        self.latency = int(latency)
        self.name = name
        self.command_events = []
        self.unsupported_modes = []
        self._outputs = {}
        self._last_word = 0

    @staticmethod
    def decode_command(cmd):
        cmd = int(cmd)
        return {
            "freq": cmd & 0xFFFFFFFF,
            "phase": (cmd >> 32) & 0xFFFFFFFF,
            "addr": (cmd >> 64) & 0xFFFF,
            "gain": AwgTuningBehaviorModel._sign_extend((cmd >> 96) & 0xFFFF, 16),
            "nsamp": (cmd >> 128) & 0xFFFF,
            "outsel": (cmd >> 144) & 0x3,
            "mode": bool((cmd >> 146) & 0x1),
            "stdysel": bool((cmd >> 147) & 0x1),
            "phrst": bool((cmd >> 148) & 0x1),
            "tmux_select": (cmd >> 152) & 0xFF,
        }

    def _pack(self, samples):
        word = 0
        mask = (1 << self.b) - 1
        for idx, sample in enumerate(samples):
            word |= (int(sample) & mask) << (idx * self.b)
        return word

    def _dds_word(self, decoded, word_index):
        phase0 = int(decoded["phase"])
        freq = int(decoded["freq"])
        gain = int(decoded["gain"])
        samples = []
        for lane in range(self.n_dds):
            phase_word = (phase0 + freq * (word_index * self.n_dds + lane)) & 0xFFFFFFFF
            angle = (phase_word / float(1 << 32)) * 2.0 * math.pi
            value = int(round(math.cos(angle) * gain))
            value = max(-(1 << (self.b - 1)), min((1 << (self.b - 1)) - 1, value))
            samples.append(value)
        return self._pack(samples)

    def accept_command(self, cycle, cmd, label=None):
        decoded = self.decode_command(cmd)
        event = CommandEvent(
            cycle=int(cycle),
            channel=0,
            raw_command=int(cmd),
            decoded=decoded,
            label=label,
            output_cycle=int(cycle) + self.latency,
        )
        self.command_events.append(event)
        nsamp = max(1, int(decoded["nsamp"]))
        n_words = max(1, (nsamp + self.n_dds - 1) // self.n_dds)

        if decoded["outsel"] == 1:
            for word_idx in range(n_words):
                self._outputs[int(cycle) + self.latency + word_idx] = self._dds_word(decoded, word_idx)
        elif decoded["outsel"] == 3:
            for word_idx in range(n_words):
                self._outputs[int(cycle) + self.latency + word_idx] = 0
        else:
            msg = "%s outsel=%d requires envelope/input data in the Python model" % (
                self.name, decoded["outsel"]
            )
            self.unsupported_modes.append(msg)
            if self.strict:
                raise UnsupportedModeError(msg)
        return event

    def step(self, cycle):
        if int(cycle) in self._outputs:
            self._last_word = self._outputs[int(cycle)]
            return self._last_word
        return 0

    def run(self, cycles, events=None):
        events = [] if events is None else list(events)
        by_cycle = {}
        for event in events:
            by_cycle.setdefault(int(event.cycle), []).append(event)
        packed = []
        lane_model = AwgTuningBehaviorModel(n_pts=self.n_dds, b=self.b)
        lanes = []
        for cycle in range(int(cycles)):
            for event in by_cycle.get(cycle, []):
                self.accept_command(cycle, event.word, event.label)
            word = self.step(cycle)
            packed.append(word)
            lanes.append(lane_model.unpack_lanes(word))
        return WaveformResult(
            packed_words=np.array(packed, dtype=object),
            lane_samples=np.array(lanes, dtype=np.int64),
            command_events=list(self.command_events),
            accepted_commands=list(self.command_events),
            dropped_commands=[],
            timing_conflicts=[],
            unsupported_modes=list(self.unsupported_modes),
            channels=[0],
        )


class AxisDynReadoutV1BehaviorModel:
    """Behavioral model for qstl dynamic readout command recognition."""

    def __init__(self, n_dds=8, strict=True, latency=0, adc_source=None, name="axis_dyn_readout_v1"):
        self.n_dds = int(n_dds)
        self.strict = bool(strict)
        self.latency = int(latency)
        self.adc_source = RfdcAdcSourceModel(n_lanes=n_dds) if adc_source is None else adc_source
        self.name = name
        self.command_events = []
        self.captured = []

    @staticmethod
    def decode_command(cmd):
        cmd = int(cmd)
        return {
            "freq": cmd & 0xFFFFFFFF,
            "phase": (cmd >> 32) & 0xFFFFFFFF,
            "nsamp": (cmd >> 64) & 0xFFFF,
            "outsel": (cmd >> 80) & 0x3,
            "mode": bool((cmd >> 82) & 0x1),
            "phrst": bool((cmd >> 83) & 0x1),
        }

    def accept_command(self, cycle, cmd, label=None):
        decoded = self.decode_command(cmd)
        event = CommandEvent(int(cycle), 0, int(cmd), decoded, label, output_cycle=int(cycle) + self.latency)
        self.command_events.append(event)
        for idx in range(max(1, decoded["nsamp"])):
            self.captured.append({
                "cycle": int(cycle) + self.latency + idx,
                "sample": self.adc_source.read_word(),
                "command": decoded,
            })
        return event


class AxisAvgBufferV13BehaviorModel:
    """Behavioral integer model for axis_avg_buffer v1.3 capture/feedback."""

    def __init__(self, b=16, accum_len=1, trace_reps=1, feedback_latency=0, name="axis_avg_buffer"):
        self.b = int(b)
        self.accum_len = max(1, int(accum_len))
        self.trace_reps = max(1, int(trace_reps))
        self.feedback_latency = int(feedback_latency)
        self.name = name
        self.raw_buffer = []
        self.avg_memory = []
        self.feedback_events = []

    def capture(self, start_cycle, iq_words, length=None):
        length = len(iq_words) if length is None else int(length)
        words = list(iq_words)[:length]
        self.raw_buffer.extend(words)
        group = self.accum_len
        for out_idx in range(0, len(words), group):
            chunk = words[out_idx:out_idx + group]
            if not chunk:
                continue
            accum_i = 0
            accum_q = 0
            for word in chunk:
                i_val = AwgTuningBehaviorModel._sign_extend(word & ((1 << self.b) - 1), self.b)
                q_val = AwgTuningBehaviorModel._sign_extend((word >> self.b) & ((1 << self.b) - 1), self.b)
                accum_i += i_val
                accum_q += q_val
            packed = (accum_q & ((1 << 64) - 1)) << 64 | (accum_i & ((1 << 64) - 1))
            self.avg_memory.append(packed)
            self.feedback_events.append(TimedCommandEvent(
                cycle=int(start_cycle) + self.feedback_latency + len(self.avg_memory) - 1,
                word=packed,
                label=self.name + "_m2_feedback",
            ))
        return list(self.feedback_events)


class QstlAwgTuningProjectSimulator:
    """Hand-coded qstl_awg_tuning behavioral topology with BD validation.

    The BD Tcl is scanned to verify expected modeled IP instances. The Python
    topology covers tProc -> TMUX -> SignalGen/AWG command routing, DAC sinks,
    dynamic readout command recognition, and avg-buffer feedback event storage.
    Non-control infrastructure such as AXI interconnect, DMA engines, PS GPIO,
    and RFDC analog behavior is listed as unsupported/non-simulated metadata
    rather than silently acting as a waveform source.
    """

    REQUIRED_MODELED_PATTERNS = {
        "axis_tproc64x32_x8": "TProcV1BehaviorModel",
        "axis_tmux_v1": "AxisTmuxV1BehaviorModel",
        "axis_signal_gen_v6": "AxisSignalGenV6BehaviorModel",
        "axis_awg_tuning_v1": "AwgTuningBehaviorModel",
        "axis_dyn_readout_v1": "AxisDynReadoutV1BehaviorModel",
        "axis_avg_buffer": "AxisAvgBufferV13BehaviorModel",
        "axis_register_slice": "AxisRegisterSliceBehaviorModel",
        "axis_broadcaster": "AxisBroadcasterBehaviorModel",
        "axis_clock_converter": "AxisClockConverterBehaviorModel",
        "axis_switch": "AxisSwitchBehaviorModel",
    }

    NON_WAVEFORM_IP_PATTERNS = [
        "axi_dma", "smartconnect", "zynq_ultra_ps_e", "axi_gpio", "axi_quad_spi",
        "proc_sys_reset", "xlconcat", "util_ds_buf", "blk_mem_gen", "usp_rf_data_converter",
        "axi_bram_ctrl", "xlconstant", "axis_set_reg", "qick_vec2bit", "mr_buffer_et",
        "axis_buffer_ddr_v1", "axis_dwidth_converter", "ddr4", "axi_intc", "c_shift_ram",
        "axi_interconnect",
    ]

    def __init__(self, bd_path=None, strict=True):
        self.bd_path = None if bd_path is None else Path(bd_path)
        self.strict = bool(strict)
        self.tmux = AxisTmuxV1BehaviorModel()
        self.signal_gens = {i: AxisSignalGenV6BehaviorModel(name="axis_signal_gen_v6_%d" % i)
                            for i in range(4)}
        self.awgs = {i: AwgTuningBehaviorModel(n_pts=16, extra_y_pipe_stages=3, channel=i)
                     for i in range(8)}
        self.readouts = {i: AxisDynReadoutV1BehaviorModel(name="axis_dyn_readout_v1_%d" % i)
                         for i in range(4)}
        self.avg_buffers = {i: AxisAvgBufferV13BehaviorModel(name="axis_avg_buffer_%d" % i)
                            for i in range(4)}
        self.dac_sinks = {}
        self.unsupported_ips = []
        self.ip_events = []
        self._signal_gen_events = {i: [] for i in self.signal_gens}
        self._awg_events = {i: [] for i in self.awgs}

    @classmethod
    def from_bd_tcl(cls, bd_tcl, soccfg=None, strict=True):
        sim = cls(bd_tcl, strict=strict)
        sim.validate_bd()
        return sim

    def _scan_created_ips(self):
        if self.bd_path is None or not self.bd_path.exists():
            return []
        text = self.bd_path.read_text(errors="ignore")
        ips = []
        for match in re.finditer(r"create_bd_cell\s+-type\s+ip\s+-vlnv\s+([^\s]+)\s+([^\]\s]+)", text):
            ips.append((match.group(2), match.group(1)))
        return ips

    def validate_bd(self):
        ips = self._scan_created_ips()
        self.unsupported_ips = []
        modeled_hits = {key: 0 for key in self.REQUIRED_MODELED_PATTERNS}
        for inst, vlnv in ips:
            key = vlnv.split(":")[-2] if ":" in vlnv else vlnv
            matched = False
            for pattern in self.REQUIRED_MODELED_PATTERNS:
                if pattern in key or pattern in vlnv:
                    modeled_hits[pattern] += 1
                    matched = True
                    break
            if matched:
                continue
            if any(pattern in key or pattern in vlnv for pattern in self.NON_WAVEFORM_IP_PATTERNS):
                continue
            self.unsupported_ips.append("%s (%s)" % (inst, vlnv))
        missing = [name for name, count in modeled_hits.items() if count == 0]
        if missing:
            self.unsupported_ips.extend("missing expected %s" % name for name in missing)
        if self.unsupported_ips and self.strict:
            raise UnsupportedIPError("; ".join(self.unsupported_ips))
        return {
            "modeled_hits": modeled_hits,
            "unsupported_ips": list(self.unsupported_ips),
        }

    def _dispatch_qstl_event(self, event):
        # qstl_awg_tuning uses TMUX select values 0..3 for signal generators and
        # 4..11 for AWG tuning instances on the DAC command fabric.
        routed = self.tmux.route(event)
        select = routed.tmux_ch & 0xFF
        if select in self.signal_gens:
            self._signal_gen_events[select].append(routed)
            self.ip_events.append(IpEvent(routed.cycle, "axis_signal_gen_v6_%d" % select,
                                          "command", {"tmux_select": select}).to_dict())
        elif 4 <= select <= 11:
            awg_idx = select - 4
            self._awg_events[awg_idx].append(routed)
            self.ip_events.append(IpEvent(routed.cycle, "axis_awg_tuning_v1_%d" % select,
                                          "command", {"tmux_select": select}).to_dict())
        else:
            msg = "qstl_awg_tuning TMUX select %d has no modeled endpoint" % select
            self.unsupported_ips.append(msg)
            if self.strict:
                raise UnsupportedIPError(msg)

    def run_events(self, events, cycles):
        self.ip_events = []
        self._signal_gen_events = {i: [] for i in self.signal_gens}
        self._awg_events = {i: [] for i in self.awgs}
        for event in events:
            self._dispatch_qstl_event(event)
        packed_by_name = {}
        lanes_by_name = {}
        commands = []
        accepted = []
        dropped = []
        conflicts = []
        unsupported_modes = []

        for idx, model in self.signal_gens.items():
            res = model.run(cycles, self._signal_gen_events[idx])
            packed_by_name["siggen%d" % idx] = res.packed_words
            lanes_by_name["siggen%d" % idx] = res.lane_samples
            commands.extend(res.command_events)
            accepted.extend(res.accepted_commands)
            unsupported_modes.extend(res.unsupported_modes)
        for idx, model in self.awgs.items():
            res = model.run(cycles, self._awg_events[idx])
            packed_by_name["awg%d" % idx] = res.packed_words
            lanes_by_name["awg%d" % idx] = res.lane_samples
            commands.extend(res.command_events)
            accepted.extend(res.accepted_commands)
            dropped.extend(res.dropped_commands)
            conflicts.extend(res.timing_conflicts)

        return WaveformResult(
            packed_words=np.array([], dtype=object),
            lane_samples=np.array([], dtype=np.int64),
            command_events=commands,
            accepted_commands=accepted,
            dropped_commands=dropped,
            timing_conflicts=conflicts,
            unsupported_ips=list(self.unsupported_ips),
            unsupported_modes=unsupported_modes,
            ip_events=list(self.ip_events),
            channel_results={
                "packed_words": packed_by_name,
                "lane_samples": lanes_by_name,
            },
        )

    def run_program(self, prog, cycles=256):
        tproc = TProcV1BehaviorModel(strict=self.strict)
        tproc.run(prog)
        return self.run_events(tproc.output_events, cycles=cycles)


__all__ = [
    "AxisAwgTuningV1",
    "TimedCommandEvent",
    "CommandEvent",
    "TimingConflict",
    "WaveformResult",
    "AwgTuningBehaviorModel",
    "TProcTimedEventSimulator",
    "UnsupportedIPError",
    "UnsupportedInstructionError",
    "UnsupportedModeError",
    "TProcV1BehaviorModel",
    "AxisTmuxV1BehaviorModel",
    "AxisRegisterSliceBehaviorModel",
    "AxisSignalGenV6BehaviorModel",
    "AxisDynReadoutV1BehaviorModel",
    "AxisAvgBufferV13BehaviorModel",
    "AxisSwitchBehaviorModel",
    "AxisBroadcasterBehaviorModel",
    "AxisClockConverterBehaviorModel",
    "RfdcDacSinkModel",
    "RfdcAdcSourceModel",
    "QstlAwgTuningProjectSimulator",
]
