"""
Driver helpers for ``axis_awg_tuning_v1``.

``axis_awg_tuning_v1`` is an AXIS-command-controlled continuous DAC sample
source. It has no AXI-Lite command registers, so this driver does not try to
write commands directly to hardware. Instead it binds the IP into the
QICK/PYNQ driver model, discovers the tProcessor connection when metadata is
available, and provides command-packing helpers for tProcessor program
generation.

The current RTL has these software-visible semantics:

* ``s_axis_tready`` is always asserted.
* ``m_axis_tready`` is ignored by the RTL.
* ``m_axis_tvalid`` remains asserted after reset.
* SET changes the current output immediately.
* RAMP starts from the internal current output and uses only target/duration.
* Command start and step fields are reserved/deprecated and ignored by RTL.
* Commands presented during an active ramp are dropped by hardware.
* Timed IDLE is not supported unless explicitly reintroduced in RTL.

Software/tProcessor programs must schedule meaningful commands so they are not
emitted during ``RAMP_ST`` unless intentional discard is desired. The
software-side ``current_value`` cache is only a convenience for prediction and
sequence construction. It can be wrong if another tProcessor program emits
commands not generated by this driver; call :meth:`reset_cache` when software
and hardware state may have diverged.
"""

import numpy as np

from qick.ip import SocIP


class AxisAwgTuningV1(SocIP):
    """Python helper driver for the AXIS-command-driven AWG tuning IP.

    The class intentionally has no direct ``send`` method: the firmware exposes
    only AXIS command and sample ports, not software-writable command registers.
    Use :meth:`pack_cmd` or the opcode-specific helpers to generate command
    words for a tProcessor program or another firmware command source.
    """

    bindto = [
        "QICK:QICK:axis_awg_tuning_v1:1.0",
        "user.org:user:axis_awg_tuning_v1:1.0",
    ]

    TPROC_PORT = "s_axis"
    OUTPUT_PORT = "m_axis"

    OP_NOP = 0b00
    OP_SET = 0b01
    OP_RAMP = 0b10
    OP_IDLE = 0b11

    HAS_IDLE = False
    CONTINUOUS_RAMP = True
    CONTINUOUS_OUTPUT = True
    CMD_READY_ALWAYS = True
    OUTPUT_READY_IGNORED = True
    DROPS_COMMANDS_WHILE_RAMPING = True
    HAS_TIMED_IDLE = False

    FIELD_MIN = -(2**31)
    FIELD_MAX = 2**31 - 1
    U32_MAX = 2**32 - 1

    def _init_config(self, description):
        """Read IP parameters from the overlay description."""
        params = description.get("parameters", {})
        n_dds = self._param_int(params, "N_DDS", 16)
        b = self._param_int(params, "B", 16)
        frac = self._param_int(params, "FRAC", 16)
        cmd_width = self._param_int(params, "CMD_WIDTH", 160)

        if cmd_width < 149:
            raise ValueError("axis_awg_tuning_v1 command width must include bits through 148")

        self.cfg["n_dds"] = n_dds
        self.cfg["samps_per_clk"] = n_dds
        self.cfg["b"] = b
        self.cfg["frac"] = frac
        self.cfg["cmd_width"] = cmd_width
        self.cfg["maxv"] = 2 ** (b - 1) - 1
        self.cfg["minv"] = -(2 ** (b - 1))
        self.cfg["has_idle"] = self.HAS_IDLE
        self.cfg["continuous_ramp"] = self.CONTINUOUS_RAMP
        self.cfg["continuous_output"] = self.CONTINUOUS_OUTPUT
        self.cfg["cmd_ready_always"] = self.CMD_READY_ALWAYS
        self.cfg["output_ready_ignored"] = self.OUTPUT_READY_IGNORED
        self.cfg["drops_commands_while_ramping"] = self.DROPS_COMMANDS_WHILE_RAMPING
        self.cfg["has_timed_idle"] = self.HAS_TIMED_IDLE
        self.cfg["tproc_ch"] = None
        self.cfg["tproc_port"] = None
        self.cfg["tproc_block"] = None
        self.cfg["tproc_type"] = None
        self.cfg["downstream"] = None

    def _init_firmware(self):
        """Initialize software-only cached state.

        There are no AXI-Lite command registers in this IP, so firmware
        initialization must not write registers.
        """
        self.current_value = 0
        self.current_valid = False
        self.last_ramp_start = None
        self.last_ramp_step = None

    @staticmethod
    def _param_int(params, name, default):
        value = params.get(name, default)
        if isinstance(value, str):
            return int(value, 0)
        return int(value)

    def configure_connections(self, soc):
        """Discover tProcessor input and downstream output connections.

        The metadata walk follows the same broad pattern as
        ``AbsPulsedSignalGen.configure_connections``. If tracing fails, the
        driver leaves connection fields as ``None`` and logs a warning rather
        than failing overlay initialization.
        """
        super().configure_connections(soc)
        self.soc = soc

        try:
            trace_result = soc.metadata.trace_back(
                self["fullpath"],
                self.TPROC_PORT,
                ["axis_tproc64x32_x8", "qick_processor", "axis_tmux_v1"],
            )
            if trace_result is not None:
                block, port, blocktype = trace_result

                if blocktype == "axis_tmux_v1":
                    self.cfg["tmux_ch"] = int(port.split("_")[0][1:])
                    ((block, port),) = soc.metadata.trace_bus(block, "s_axis")
                    blocktype = soc.metadata.mod2type(block)

                self.cfg["tproc_block"] = block
                self.cfg["tproc_port"] = port
                self.cfg["tproc_type"] = blocktype

                tproc = soc._get_block(block)
                if hasattr(tproc, "port2ch"):
                    self.cfg["tproc_ch"], _ = tproc.port2ch(port)
        except Exception as exc:
            self.logger.warning("could not trace AWG tuning tProcessor connection: %s", exc)

        try:
            peers = soc.metadata.trace_bus(self["fullpath"], self.OUTPUT_PORT)
            downstream = []
            for peer in peers:
                if len(peer) == 2:
                    block, port = peer
                    try:
                        blocktype = soc.metadata.mod2type(block)
                    except Exception:
                        blocktype = None
                    downstream.append((block, port, blocktype))
                else:
                    downstream.append(tuple(peer))
            self.cfg["downstream"] = downstream
            self.cfg["output"] = downstream
        except Exception as exc:
            self.logger.warning("could not trace AWG tuning output connection: %s", exc)

    def _check_int(self, value, name):
        """Return ``value`` as a Python int, rejecting booleans/non-integers."""
        if isinstance(value, (bool, np.bool_)) or not isinstance(value, (int, np.integer)):
            raise ValueError(f"{name} must be an integer")
        return int(value)

    def _to_u32_signed(self, value, name):
        """Convert a signed 32-bit field to unsigned two's-complement form."""
        value = self._check_int(value, name)
        if value < self.FIELD_MIN or value > self.FIELD_MAX:
            raise ValueError(f"{name}={value} does not fit in signed 32 bits")
        return value & self.U32_MAX

    def _to_u32_unsigned(self, value, name):
        """Validate and convert an unsigned 32-bit field."""
        value = self._check_int(value, name)
        if value < 0 or value > self.U32_MAX:
            raise ValueError(f"{name}={value} does not fit in unsigned 32 bits")
        return value

    def _check_bool(self, value, name):
        if not isinstance(value, (bool, np.bool_)):
            raise ValueError(f"{name} must be a bool")
        return bool(value)

    @staticmethod
    def _from_u32_signed(value):
        value &= 0xFFFFFFFF
        if value & 0x80000000:
            return value - 0x100000000
        return value

    @staticmethod
    def _div_trunc_zero(num, den):
        """Signed integer division matching SystemVerilog truncation to zero."""
        if den == 0:
            raise ZeroDivisionError("division by zero")
        sign = -1 if (num < 0) ^ (den < 0) else 1
        return sign * (abs(num) // abs(den))

    def clip_sample(self, value):
        """Clip a value to the configured signed output sample range."""
        value = self._check_int(value, "value")
        return max(self["minv"], min(self["maxv"], value))

    def calc_step(self, start, target, duration):
        """Calculate the signed fixed-point RAMP step used by the RTL.

        Python ``//`` floors negative divisions, but SystemVerilog signed
        division truncates toward zero. This helper uses truncation toward zero
        to match the RTL and testbench. ``ramp_cmd`` uses this for software
        prediction/debug only; the current RTL computes the effective step
        internally.
        """
        start = self._check_int(start, "start")
        target = self._check_int(target, "target")
        duration = self._to_u32_unsigned(duration, "duration")
        self._to_u32_signed(start, "start")
        self._to_u32_signed(target, "target")

        if duration <= 1:
            return 0

        numerator = (target - start) << self["frac"]
        step = self._div_trunc_zero(numerator, duration - 1)
        self._to_u32_signed(step, "step")
        return step

    def pack_cmd(self, target=0, start=0, duration=0, step=0,
                 opcode=None, hold_zero=False, clear=False):
        """Pack a 160-bit AWG tuning command word into a Python int.

        This low-level packer includes all fields, including the
        reserved/deprecated RAMP start and step fields. For normal use, call
        :meth:`set_cmd` or :meth:`ramp_cmd`. The current RTL ignores the RAMP
        start/step fields and computes the effective start/step internally.
        """
        if opcode is None:
            opcode = self.OP_NOP

        target_u = self._to_u32_signed(target, "target")
        start_u = self._to_u32_signed(start, "reserved_start")
        duration_u = self._to_u32_unsigned(duration, "duration")
        step_u = self._to_u32_signed(step, "reserved_step")
        opcode = self._check_int(opcode, "opcode")
        if opcode < 0 or opcode > 0b11:
            raise ValueError("opcode must fit in 2 bits")
        hold_zero = self._check_bool(hold_zero, "hold_zero")
        clear = self._check_bool(clear, "clear")

        cmd = 0
        cmd |= target_u
        cmd |= start_u << 32
        cmd |= duration_u << 64
        cmd |= step_u << 96
        cmd |= opcode << 144
        cmd |= int(hold_zero) << 146
        cmd |= int(clear) << 148

        if cmd >= (1 << self["cmd_width"]):
            raise ValueError("packed command exceeds configured CMD_WIDTH")
        return cmd

    def nop_cmd(self, clear=False):
        """Return a NOP command word.

        In the current RTL, NOP is immediate and does not modify current value.
        The ``clear`` bit is packed if requested but is ignored by the RTL.
        """
        return self.pack_cmd(opcode=self.OP_NOP, clear=clear)

    def set_cmd(self, output_value, *, hold_zero=False, clear=False, saturate=False):
        """Return a SET command word and update the software cache.

        ``output_value`` is a signed 32-bit logical target. If
        ``saturate=True``, the value is first clipped to the configured output
        sample range. ``hold_zero`` matches the current RTL SET behavior: the
        SET word emits ``output_value``, then the held output becomes zero.
        ``clear`` is packed for field visibility but is ignored by current RTL.
        """
        value = self._check_int(output_value, "output_value")
        if saturate:
            value = self.clip_sample(value)
        self._to_u32_signed(value, "output_value")

        cmd = self.pack_cmd(target=value, opcode=self.OP_SET,
                            hold_zero=hold_zero, clear=clear)
        self.current_value = 0 if hold_zero else value
        self.current_valid = True
        return cmd

    def ramp_cmd(self, final_output_value, ramp_duration, *, hold_zero=False, clear=False):
        """Return a RAMP command word and update the software cache.

        The public API exposes only the final output value and scalar-sample
        duration because the current RTL ignores command start/step fields.
        The effective ramp starts from the IP's internal current output. This
        method uses the software ``current_value`` cache only for prediction and
        to reject ambiguous sequences.

        Commands issued during an active ramp are dropped by hardware. This
        method only packs a command word; it does not schedule tProcessor
        timing.
        """
        if hold_zero:
            raise NotImplementedError("RAMP hold_zero is not implemented by the current RTL")

        target = self._check_int(final_output_value, "final_output_value")
        duration = self._to_u32_unsigned(ramp_duration, "ramp_duration")
        self._to_u32_signed(target, "final_output_value")

        if not self.current_valid:
            raise ValueError(
                "software current-value cache is invalid; call reset_cache(value, valid=True) "
                "or issue a SET command through this driver before creating a RAMP command"
            )

        start_value = self.current_value
        self._to_u32_signed(start_value, "current_value")
        self.last_ramp_start = start_value
        self.last_ramp_step = self.calc_step(start_value, target, duration)

        cmd = self.pack_cmd(target=target, start=0, duration=duration,
                            step=0, opcode=self.OP_RAMP,
                            hold_zero=hold_zero, clear=clear)
        self.current_value = target
        self.current_valid = True
        return cmd

    def idle_cmd(self, duration=0, clear=False):
        """Timed IDLE is unsupported by the current RTL."""
        raise NotImplementedError(
            "axis_awg_tuning_v1 no longer supports timed IDLE; "
            "schedule timing in the tProcessor program instead"
        )

    def reset_cache(self, value=0, valid=False):
        """Reset the software-side current-value cache."""
        value = self._check_int(value, "value")
        self._to_u32_signed(value, "value")
        self.current_value = value
        self.current_valid = bool(valid)
        self.last_ramp_start = None
        self.last_ramp_step = None

    def make_sequence(self, instructions):
        """Pack a list of instruction dictionaries into command words.

        Supported forms include ``{"op": "set", "value": ...}``,
        ``{"op": "ramp", "target": ..., "duration": ...}``, and
        ``{"op": "nop"}``. This only packs command words; it does not
        schedule tProcessor timing. Since commands during a ramp are dropped by
        hardware, user code must emit subsequent meaningful commands only after
        the active ramp has completed.
        """
        cmds = []
        for inst in instructions:
            op = inst.get("op")
            if op == "nop":
                cmds.append(self.nop_cmd(clear=inst.get("clear", False)))
            elif op == "set":
                cmds.append(self.set_cmd(
                    inst["value"],
                    hold_zero=inst.get("hold_zero", False),
                    clear=inst.get("clear", False),
                    saturate=inst.get("saturate", False),
                ))
            elif op == "ramp":
                if "start" in inst or "step" in inst:
                    raise ValueError(
                        "start/step fields are deprecated and ignored by the current RTL; "
                        "remove them from ramp instructions"
                    )
                cmds.append(self.ramp_cmd(
                    inst["target"],
                    inst["duration"],
                    hold_zero=inst.get("hold_zero", False),
                    clear=inst.get("clear", False),
                ))
            elif op == "idle":
                cmds.append(self.idle_cmd(inst.get("duration", 0), clear=inst.get("clear", False)))
            else:
                raise ValueError(f"unknown AWG tuning op {op!r}")
        return cmds

    def cmd_to_words(self, cmd):
        """Return five 32-bit words, least-significant word first."""
        cmd = self._check_int(cmd, "cmd")
        if cmd < 0 or cmd >= (1 << self["cmd_width"]):
            raise ValueError("cmd is outside the configured command width")
        return [(cmd >> (32 * i)) & 0xFFFFFFFF for i in range(5)]

    def format_cmd(self, cmd):
        """Decode a packed command into a readable dictionary.

        The RAMP start and step command fields are reported as reserved and
        deprecated because the current RTL ignores them.
        """
        cmd = self._check_int(cmd, "cmd")
        if cmd < 0 or cmd >= (1 << self["cmd_width"]):
            raise ValueError("cmd is outside the configured command width")

        opcode = (cmd >> 144) & 0b11
        names = {
            self.OP_NOP: "nop",
            self.OP_SET: "set",
            self.OP_RAMP: "ramp",
            self.OP_IDLE: "idle",
        }
        reserved_start = self._from_u32_signed(cmd >> 32)
        reserved_step = self._from_u32_signed(cmd >> 96)
        return {
            "opcode": opcode,
            "op": names.get(opcode, "unknown"),
            "target": self._from_u32_signed(cmd),
            "reserved_start": reserved_start,
            "duration": (cmd >> 64) & 0xFFFFFFFF,
            "reserved_step": reserved_step,
            "start_deprecated": reserved_start,
            "step_deprecated": reserved_step,
            "hold_zero": bool((cmd >> 146) & 0x1),
            "clear": bool((cmd >> 148) & 0x1),
        }


__all__ = ["AxisAwgTuningV1"]
