"""Reconstruct the production digital datapath from its published HWH and Tcl.

PS, RFDC, DDR PHY and host DMA engines become testbench interfaces. The actual
tProcessor, all DAC generators, routing, readouts, FIR and capture IPs remain.
"""
import hashlib
import json
import re
from collections import defaultdict
from pathlib import Path
import xml.etree.ElementTree as ET

HERE = Path(__file__).resolve().parent
BASE = HERE.parent / 'qstl_awg_tuning_fir_1msps_iq64_sq_pulse'
TYPES = {
    'axis_tproc64x32_x8', 'axis_awg_tuning_v1', 'axis_square_pulse_v1',
    'axis_signal_gen_v6', 'axis_tmux_v1', 'axis_register_slice',
    'axis_register_slice_nb', 'axis_set_reg', 'qick_vec2bit',
    'axis_dyn_readout_v1', 'axis_broadcaster', 'axis_clock_converter',
    'axis_avg_buffer', 'axis_switch', 'mr_buffer_et', 'c_shift_ram',
    'axis_fir_decim_300to1_v2', 'axis_buffer_ddr_sample_v3',
    'axis_trigger_sync_v1', 'xlconstant',
}


def main():
    root = ET.parse(BASE / 'bitstream.hwh')
    clock_nets = {p.get('SIGNAME'): int(p.get('CLKFREQUENCY'))
                  for p in root.findall('.//MODULE/PORTS/PORT') if p.get('CLKFREQUENCY')}
    tcl = (BASE / 'bd_2023-1.tcl').read_text()
    modules = [m for m in root.findall('.//MODULE') if m.get('MODTYPE') in TYPES
               and (m.get('FULLNAME').count('/') == 1
                    or m.get('FULLNAME').startswith('/ddr4/'))]
    lines = ['# Generated by build_design.py from production HWH/Tcl.',
             'create_bd_design sim_bd', '''proc expose_bus {pin name} {
    set before [get_bd_intf_ports -quiet]
    make_bd_intf_pins_external [get_bd_intf_pins $pin]
    foreach port [get_bd_intf_ports] {
        if {[lsearch -exact $before $port] < 0} {set_property name $name $port; return}
    }
    error "No external interface created for $pin"
}''']
    buses, signals, clocks = defaultdict(list), defaultdict(list), defaultdict(list)
    metadata = dict(source_hwh_sha256=hashlib.sha256((BASE/'bitstream.hwh').read_bytes()).hexdigest(),
                    cells={}, external_buses={}, external_signals={})
    creations = list(re.finditer(r'set (\w+) \[ create_bd_cell -type ip -vlnv (\S+) (\w+) \]', tcl))
    for m in modules:
        path = m.get('FULLNAME').strip('/')
        name = path.replace('/', '_')
        inst = path.split('/')[-1]
        matches = [x for x in creations if x.group(3) == inst]
        if len(matches) != 1:
            # xlconstant_0 also exists in the removed RF-board hierarchy.
            matches = [x for x in matches if x.start() > tcl.index('proc create_root_design')]
        assert len(matches) == 1, (path, len(matches))
        creation = matches[0]
        next_pos = next((x.start() for x in creations if x.start() > creation.start()), len(tcl))
        block = tcl[creation.end():next_pos]
        lines.append(f'set {inst} [create_bd_cell -type ip -vlnv {m.get("VLNV")} {name}]')
        properties = re.findall(r'set_property -dict \[list (.*?)\]\s+\$'+re.escape(inst)+r'\b', block, re.S)
        for prop in properties:
            lines.append(f'set_property -dict [list {prop}] ${inst}')
        for key, value in re.findall(r'set_property (CONFIG\.\w+) (\{[^}]*\}|\S+) \$'+re.escape(inst)+r'\b', block):
            lines.append(f'set_property {key} {value} ${inst}')
        metadata['cells'][name] = dict(source_path=path, type=m.get('MODTYPE'),
            parameters={p.get('NAME'):p.get('VALUE') for p in m.findall('./PARAMETERS/PARAMETER')})
        bus_pins = set()
        for b in m.findall('./BUSINTERFACES/BUSINTERFACE'):
            bus_name = b.get('BUSNAME')
            if not bus_name or bus_name == '__NOC__':
                bus_name = name+'/'+b.get('NAME')
            buses[bus_name].append((name+'/'+b.get('NAME'), b))
            bus_pins.update(p.get('PHYSICAL') for p in b.findall('./PORTMAPS/PORTMAP'))
        for p in m.findall('./PORTS/PORT'):
            if p.get('NAME') in bus_pins:
                continue
            pin = name+'/'+p.get('NAME')
            if p.get('SIGIS') == 'clk' and p.get('DIR') == 'I':
                clocks[clock_nets[p.get('SIGNAME')]].append(pin)
            elif p.get('DIR') == 'I' and ('aresetn' in p.get('NAME')):
                signals['simulation_resetn'].append((pin, p))
            else:
                signal_name = p.get('SIGNAME')
                if not signal_name or signal_name == '__NOC__':
                    signal_name = pin
                signals[signal_name].append((pin, p))
    for bus, items in buses.items():
        if len(items) > 1:
            lines.append('connect_bd_intf_net '+' '.join(f'[get_bd_intf_pins {pin}]' for pin,_ in items))
        else:
            pin, b = items[0]
            name = 'ext_'+pin.replace('/', '_')
            lines.append(f'expose_bus {pin} {name}')
            if b.get('TYPE') == 'TARGET' and ':axis:' in b.get('VLNV',''):
                params = {p.get('NAME'):p.get('VALUE') for p in b.findall('PARAMETER')}
                keys = ('TDATA_NUM_BYTES','TDEST_WIDTH','TID_WIDTH','TUSER_WIDTH',
                        'HAS_TREADY','HAS_TSTRB','HAS_TKEEP','HAS_TLAST','FREQ_HZ')
                props = ' '.join(f'CONFIG.{k} {{{params[k]}}}' for k in keys if k in params)
                lines.append(f'set_property -dict [list {props}] [get_bd_intf_ports {name}]')
            metadata['external_buses'][name] = dict(pin=pin, type=b.get('TYPE'),
                vlnv=b.get('VLNV'), parameters={p.get('NAME'):p.get('VALUE') for p in b.findall('PARAMETER')})
    for signal, items in signals.items():
        outputs = [(pin,p) for pin,p in items if p.get('DIR') == 'O']
        if outputs:
            lines.append('connect_bd_net '+' '.join(f'[get_bd_pins {pin}]' for pin,_ in items)) if len(items)>1 else None
            if len(items)>1 and not outputs[0][0].startswith('qick_vec2bit_0/dout'):
                continue
            pin,p = outputs[0]
        else:
            pin,p = items[0]
        # Export undriven inputs, terminal outputs and observable GPIO bits.
        name = 'resetn' if signal == 'simulation_resetn' else 'ext_'+pin.replace('/', '_')
        width = abs(int(p.get('LEFT',0))-int(p.get('RIGHT',0)))+1
        direction = p.get('DIR')
        width_arg = f'-from {width-1} -to 0' if width>1 else ''
        reset_arg = '-type rst' if name == 'resetn' else ''
        lines.append(f'create_bd_port -dir {direction} {width_arg} {reset_arg} {name}')
        lines.append(f'connect_bd_net [get_bd_ports {name}] '+' '.join(f'[get_bd_pins {pin}]' for pin,_ in items))
        metadata['external_signals'][name] = dict(pins=[pin for pin,_ in items], direction=direction, width=width)
    for frequency,pins in clocks.items():
        name = f'clk_{frequency}'
        lines.append(f'create_bd_port -dir I -type clk -freq_hz {frequency} {name}')
        associated = [name for name, bus in metadata['external_buses'].items()
                      if int(bus['parameters'].get('FREQ_HZ') or 0) == frequency]
        if associated:
            lines.append(f'set_property CONFIG.ASSOCIATED_BUSIF {{{":".join(associated)}}} [get_bd_ports {name}]')
        lines.append(f'set_property CONFIG.ASSOCIATED_RESET resetn [get_bd_ports {name}]')
        lines.append(f'connect_bd_net [get_bd_ports {name}] '+' '.join(f'[get_bd_pins {pin}]' for pin in pins))
    metadata['clocks'] = {str(k):v for k,v in clocks.items()}
    lines.extend(['set_property CONFIG.POLARITY ACTIVE_LOW [get_bd_ports resetn]',
                  'assign_bd_address', 'validate_bd_design', 'save_bd_design'])
    (HERE/'design.tcl').write_text('\n'.join(lines)+'\n')
    (HERE/'topology.json').write_text(json.dumps(metadata,indent=2)+'\n')
    print(f'{len(modules)} real IP cells; {len(buses)} buses; clocks {list(clocks)}')


if __name__ == '__main__':
    main()
