// Authors: Jeonghyun Park (jeonghyun.park@ubc.ca or alexist@snu.ac.kr), Farbod
// Generated by design_filter.py. Do not edit coefficient values by hand.
`timescale 1ns/1ps
package notch_decim_1m_to50k_coeffs_pkg;
    localparam int FIR_COEFF_WIDTH = 18;
    localparam int FIR_COEFF_FRAC_BITS = 17;
    localparam int FIR_ACC_WIDTH = 48;
    localparam int STAGE0_DECIM = 10;
    localparam int STAGE0_TAPS = 113;
    localparam int STAGE1_DECIM = 2;
    localparam int STAGE1_TAPS = 125;
    localparam int SOS_COEFF_WIDTH = 32;
    localparam int SOS_COEFF_FRAC_BITS = 30;
    localparam int INPUT_SAMPLE_RATE_HZ = 1000000;
    localparam int OUTPUT_SAMPLE_RATE_HZ = 50000;
    localparam int DECIMATION = 20;
    localparam int NOTCH_SECTIONS = 40;
    localparam int NOTCH_HARMONICS = 20;
    localparam int NOTCH_REPEATS = 2;
    localparam int DEFAULT_TRIGGER_DELAY_SAMPLES = 50;

    function automatic logic signed [FIR_COEFF_WIDTH-1:0] fir_coeff(input int stage, input int index);
        fir_coeff = '0;
        case (stage)
            0: begin
                case (index)
                    0: fir_coeff = 18'sd0;
                    1: fir_coeff = 18'sd0;
                    2: fir_coeff = 18'sd0;
                    3: fir_coeff = 18'sd0;
                    4: fir_coeff = 18'sd0;
                    5: fir_coeff = 18'sd2;
                    6: fir_coeff = 18'sd4;
                    7: fir_coeff = 18'sd6;
                    8: fir_coeff = 18'sd9;
                    9: fir_coeff = 18'sd13;
                    10: fir_coeff = 18'sd15;
                    11: fir_coeff = 18'sd16;
                    12: fir_coeff = 18'sd14;
                    13: fir_coeff = 18'sd9;
                    14: fir_coeff = -18'sd1;
                    15: fir_coeff = -18'sd17;
                    16: fir_coeff = -18'sd37;
                    17: fir_coeff = -18'sd60;
                    18: fir_coeff = -18'sd85;
                    19: fir_coeff = -18'sd108;
                    20: fir_coeff = -18'sd124;
                    21: fir_coeff = -18'sd129;
                    22: fir_coeff = -18'sd117;
                    23: fir_coeff = -18'sd85;
                    24: fir_coeff = -18'sd30;
                    25: fir_coeff = 18'sd48;
                    26: fir_coeff = 18'sd145;
                    27: fir_coeff = 18'sd256;
                    28: fir_coeff = 18'sd368;
                    29: fir_coeff = 18'sd469;
                    30: fir_coeff = 18'sd542;
                    31: fir_coeff = 18'sd570;
                    32: fir_coeff = 18'sd538;
                    33: fir_coeff = 18'sd432;
                    34: fir_coeff = 18'sd247;
                    35: fir_coeff = -18'sd16;
                    36: fir_coeff = -18'sd345;
                    37: fir_coeff = -18'sd720;
                    38: fir_coeff = -18'sd1108;
                    39: fir_coeff = -18'sd1468;
                    40: fir_coeff = -18'sd1753;
                    41: fir_coeff = -18'sd1913;
                    42: fir_coeff = -18'sd1898;
                    43: fir_coeff = -18'sd1667;
                    44: fir_coeff = -18'sd1188;
                    45: fir_coeff = -18'sd444;
                    46: fir_coeff = 18'sd560;
                    47: fir_coeff = 18'sd1803;
                    48: fir_coeff = 18'sd3239;
                    49: fir_coeff = 18'sd4806;
                    50: fir_coeff = 18'sd6426;
                    51: fir_coeff = 18'sd8009;
                    52: fir_coeff = 18'sd9466;
                    53: fir_coeff = 18'sd10707;
                    54: fir_coeff = 18'sd11655;
                    55: fir_coeff = 18'sd12249;
                    56: fir_coeff = 18'sd12452;
                    57: fir_coeff = 18'sd12249;
                    58: fir_coeff = 18'sd11655;
                    59: fir_coeff = 18'sd10707;
                    60: fir_coeff = 18'sd9466;
                    61: fir_coeff = 18'sd8009;
                    62: fir_coeff = 18'sd6426;
                    63: fir_coeff = 18'sd4806;
                    64: fir_coeff = 18'sd3239;
                    65: fir_coeff = 18'sd1803;
                    66: fir_coeff = 18'sd560;
                    67: fir_coeff = -18'sd444;
                    68: fir_coeff = -18'sd1188;
                    69: fir_coeff = -18'sd1667;
                    70: fir_coeff = -18'sd1898;
                    71: fir_coeff = -18'sd1913;
                    72: fir_coeff = -18'sd1753;
                    73: fir_coeff = -18'sd1468;
                    74: fir_coeff = -18'sd1108;
                    75: fir_coeff = -18'sd720;
                    76: fir_coeff = -18'sd345;
                    77: fir_coeff = -18'sd16;
                    78: fir_coeff = 18'sd247;
                    79: fir_coeff = 18'sd432;
                    80: fir_coeff = 18'sd538;
                    81: fir_coeff = 18'sd570;
                    82: fir_coeff = 18'sd542;
                    83: fir_coeff = 18'sd469;
                    84: fir_coeff = 18'sd368;
                    85: fir_coeff = 18'sd256;
                    86: fir_coeff = 18'sd145;
                    87: fir_coeff = 18'sd48;
                    88: fir_coeff = -18'sd30;
                    89: fir_coeff = -18'sd85;
                    90: fir_coeff = -18'sd117;
                    91: fir_coeff = -18'sd129;
                    92: fir_coeff = -18'sd124;
                    93: fir_coeff = -18'sd108;
                    94: fir_coeff = -18'sd85;
                    95: fir_coeff = -18'sd60;
                    96: fir_coeff = -18'sd37;
                    97: fir_coeff = -18'sd17;
                    98: fir_coeff = -18'sd1;
                    99: fir_coeff = 18'sd9;
                    100: fir_coeff = 18'sd14;
                    101: fir_coeff = 18'sd16;
                    102: fir_coeff = 18'sd15;
                    103: fir_coeff = 18'sd13;
                    104: fir_coeff = 18'sd9;
                    105: fir_coeff = 18'sd6;
                    106: fir_coeff = 18'sd4;
                    107: fir_coeff = 18'sd2;
                    108: fir_coeff = 18'sd0;
                    109: fir_coeff = 18'sd0;
                    110: fir_coeff = 18'sd0;
                    111: fir_coeff = 18'sd0;
                    112: fir_coeff = 18'sd0;
                    default: ;
                endcase
            end
            1: begin
                case (index)
                    0: fir_coeff = 18'sd0;
                    1: fir_coeff = 18'sd0;
                    2: fir_coeff = 18'sd0;
                    3: fir_coeff = 18'sd1;
                    4: fir_coeff = 18'sd1;
                    5: fir_coeff = -18'sd2;
                    6: fir_coeff = -18'sd2;
                    7: fir_coeff = 18'sd4;
                    8: fir_coeff = 18'sd6;
                    9: fir_coeff = -18'sd4;
                    10: fir_coeff = -18'sd11;
                    11: fir_coeff = 18'sd2;
                    12: fir_coeff = 18'sd18;
                    13: fir_coeff = 18'sd4;
                    14: fir_coeff = -18'sd27;
                    15: fir_coeff = -18'sd16;
                    16: fir_coeff = 18'sd33;
                    17: fir_coeff = 18'sd35;
                    18: fir_coeff = -18'sd35;
                    19: fir_coeff = -18'sd63;
                    20: fir_coeff = 18'sd26;
                    21: fir_coeff = 18'sd96;
                    22: fir_coeff = 18'sd0;
                    23: fir_coeff = -18'sd130;
                    24: fir_coeff = -18'sd47;
                    25: fir_coeff = 18'sd156;
                    26: fir_coeff = 18'sd118;
                    27: fir_coeff = -18'sd162;
                    28: fir_coeff = -18'sd212;
                    29: fir_coeff = 18'sd135;
                    30: fir_coeff = 18'sd320;
                    31: fir_coeff = -18'sd59;
                    32: fir_coeff = -18'sd427;
                    33: fir_coeff = -18'sd75;
                    34: fir_coeff = 18'sd511;
                    35: fir_coeff = 18'sd273;
                    36: fir_coeff = -18'sd543;
                    37: fir_coeff = -18'sd528;
                    38: fir_coeff = 18'sd489;
                    39: fir_coeff = 18'sd823;
                    40: fir_coeff = -18'sd316;
                    41: fir_coeff = -18'sd1121;
                    42: fir_coeff = 18'sd0;
                    43: fir_coeff = 18'sd1375;
                    44: fir_coeff = 18'sd476;
                    45: fir_coeff = -18'sd1521;
                    46: fir_coeff = -18'sd1112;
                    47: fir_coeff = 18'sd1484;
                    48: fir_coeff = 18'sd1887;
                    49: fir_coeff = -18'sd1180;
                    50: fir_coeff = -18'sd2764;
                    51: fir_coeff = 18'sd510;
                    52: fir_coeff = 18'sd3685;
                    53: fir_coeff = 18'sd656;
                    54: fir_coeff = -18'sd4582;
                    55: fir_coeff = -18'sd2547;
                    56: fir_coeff = 18'sd5381;
                    57: fir_coeff = 18'sd5721;
                    58: fir_coeff = -18'sd6011;
                    59: fir_coeff = -18'sd12254;
                    60: fir_coeff = 18'sd6415;
                    61: fir_coeff = 18'sd41157;
                    62: fir_coeff = 18'sd58982;
                    63: fir_coeff = 18'sd41157;
                    64: fir_coeff = 18'sd6415;
                    65: fir_coeff = -18'sd12254;
                    66: fir_coeff = -18'sd6011;
                    67: fir_coeff = 18'sd5721;
                    68: fir_coeff = 18'sd5381;
                    69: fir_coeff = -18'sd2547;
                    70: fir_coeff = -18'sd4582;
                    71: fir_coeff = 18'sd656;
                    72: fir_coeff = 18'sd3685;
                    73: fir_coeff = 18'sd510;
                    74: fir_coeff = -18'sd2764;
                    75: fir_coeff = -18'sd1180;
                    76: fir_coeff = 18'sd1887;
                    77: fir_coeff = 18'sd1484;
                    78: fir_coeff = -18'sd1112;
                    79: fir_coeff = -18'sd1521;
                    80: fir_coeff = 18'sd476;
                    81: fir_coeff = 18'sd1375;
                    82: fir_coeff = 18'sd0;
                    83: fir_coeff = -18'sd1121;
                    84: fir_coeff = -18'sd316;
                    85: fir_coeff = 18'sd823;
                    86: fir_coeff = 18'sd489;
                    87: fir_coeff = -18'sd528;
                    88: fir_coeff = -18'sd543;
                    89: fir_coeff = 18'sd273;
                    90: fir_coeff = 18'sd511;
                    91: fir_coeff = -18'sd75;
                    92: fir_coeff = -18'sd427;
                    93: fir_coeff = -18'sd59;
                    94: fir_coeff = 18'sd320;
                    95: fir_coeff = 18'sd135;
                    96: fir_coeff = -18'sd212;
                    97: fir_coeff = -18'sd162;
                    98: fir_coeff = 18'sd118;
                    99: fir_coeff = 18'sd156;
                    100: fir_coeff = -18'sd47;
                    101: fir_coeff = -18'sd130;
                    102: fir_coeff = 18'sd0;
                    103: fir_coeff = 18'sd96;
                    104: fir_coeff = 18'sd26;
                    105: fir_coeff = -18'sd63;
                    106: fir_coeff = -18'sd35;
                    107: fir_coeff = 18'sd35;
                    108: fir_coeff = 18'sd33;
                    109: fir_coeff = -18'sd16;
                    110: fir_coeff = -18'sd27;
                    111: fir_coeff = 18'sd4;
                    112: fir_coeff = 18'sd18;
                    113: fir_coeff = 18'sd2;
                    114: fir_coeff = -18'sd11;
                    115: fir_coeff = -18'sd4;
                    116: fir_coeff = 18'sd6;
                    117: fir_coeff = 18'sd4;
                    118: fir_coeff = -18'sd2;
                    119: fir_coeff = -18'sd2;
                    120: fir_coeff = 18'sd1;
                    121: fir_coeff = 18'sd1;
                    122: fir_coeff = 18'sd0;
                    123: fir_coeff = 18'sd0;
                    124: fir_coeff = 18'sd0;
                    default: ;
                endcase
            end
            default: ;
        endcase
    endfunction

    function automatic logic signed [SOS_COEFF_WIDTH-1:0] notch_coeff(input int section, input int coefficient);
        notch_coeff = '0;
        case (section)
            0: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2147152788;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2147152788;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            1: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2147152788;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2147152788;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            2: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2146969692;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2146969692;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            3: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2146969692;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2146969692;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            4: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2146664544;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2146664544;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            5: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2146664544;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2146664544;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            6: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2146237361;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2146237361;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            7: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2146237361;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2146237361;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            8: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2145688167;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2145688167;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            9: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2145688167;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2145688167;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            10: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2145016994;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2145016994;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            11: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2145016994;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2145016994;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            12: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2144223879;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2144223879;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            13: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2144223879;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2144223879;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            14: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2143308868;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2143308868;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            15: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2143308868;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2143308868;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            16: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2142272013;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2142272013;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            17: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2142272013;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2142272013;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            18: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2141113373;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2141113373;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            19: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2141113373;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2141113373;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            20: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2139833013;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2139833013;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            21: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2139833013;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2139833013;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            22: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2138431006;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2138431006;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            23: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2138431006;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2138431006;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            24: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2136907433;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2136907433;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            25: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2136907433;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2136907433;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            26: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2135262379;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2135262379;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            27: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2135262379;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2135262379;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            28: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2133495939;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2133495939;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            29: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2133495939;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2133495939;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            30: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2131608212;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2131608212;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            31: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2131608212;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2131608212;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            32: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2129599306;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2129599306;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            33: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2129599306;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2129599306;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            34: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2127469335;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2127469335;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            35: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2127469335;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2127469335;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            36: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2125218421;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2125218421;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            37: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2125218421;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2125218421;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            38: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2122846691;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2122846691;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            39: begin
                case (coefficient)
                    0: notch_coeff = 32'sd1073606911;
                    1: notch_coeff = -32'sd2122846691;
                    2: notch_coeff = 32'sd1073606911;
                    3: notch_coeff = -32'sd2122846691;
                    4: notch_coeff = 32'sd1073471997;
                    default: ;
                endcase
            end
            default: ;
        endcase
    endfunction

endpackage
