// Generated by rc_precomp_validation/generate_rtl.py.
// Trapezoidal integration; 48 fractional bits, 24 signed integer bits.
// Every word contains N_PTS consecutive scalar samples, lane zero first.
// Both enabled and bypass paths have 11 register stages. No division.
`timescale 1ns/1ps
`default_nettype none
module square_rc_precomp #(parameter integer N_PTS=16)(
    input wire clk, rstn, valid_i, enable_i, clear_i, active_i,
    input wire [N_PTS*16-1:0] samples_i,
    input wire [47:0] half_step_i,
    output logic [N_PTS*16-1:0] samples_o,
    output logic valid_o,
    output logic clipped_o
);
    localparam integer SW=54, MW=54;
    logic signed [SW-1:0] prefix [0:4][N_PTS];
    logic signed [48:0] previous;
    wire signed [48:0] signed_steps[N_PTS];
    for(genvar j=0;j<N_PTS;j=j+1) begin
        assign signed_steps[j]=(!active_i || samples_i[16*j+:16]==0) ? 49'sd0 :
            (samples_i[16*j+15] ? -$signed({1'b0,half_step_i}) : $signed({1'b0,half_step_i}));
    end
    
    logic signed [MW-1:0] product1 [N_PTS];
    logic signed [MW-1:0] product2 [N_PTS], product3 [N_PTS];
    logic signed [71:0] integral, lane_integral[N_PTS], corrected[N_PTS];
    logic [N_PTS*16-1:0] raw [0:9];
    logic [9:0] enabled, cleared, active, valid;
    localparam logic signed [71:0] MAX_ACC={1'b0,{71{1'b1}}};
    localparam logic signed [71:0] MIN_ACC={1'b1,{71{1'b0}}};
    wire signed [71:0] base = cleared[7] ? 72'sd0 : integral;
    wire signed [72:0] next_sum = {base[71],base} +
        {{(73-MW){product3[N_PTS-1][MW-1]}},product3[N_PTS-1]};

    function automatic signed [71:0] acc_sat(input logic signed [72:0] value);
        if (value[72] != value[71]) acc_sat=value[72] ? MIN_ACC : MAX_ACC;
        else acc_sat=value[71:0];
    endfunction
    function automatic signed [15:0] dac_sat(input logic signed [71:0] value);
        logic signed [71:0] quantized;
        begin
            // Round to the nearest effective DAC code (4), ties toward +inf.
            quantized=(value+72'sh000002000000000000) >>> 50;
            if (value > (72'sd32764 <<< 48)) quantized=8191;
            if (value < (-72'sd32768 <<< 48)) quantized=-8192;
            if (quantized > 8191) dac_sat=16'sd32764;
            else if (quantized < -8192) dac_sat=-16'sd32768;
            else dac_sat={quantized[13:0],2'b00};
        end
    endfunction

    always_ff @(posedge clk) begin
        if (!rstn) begin
            integral<=0; previous<=0;
            enabled<=0; cleared<=0; active<=0; valid<=0;
            samples_o<=0; valid_o<=0; clipped_o<=0;
            
            for(integer s=0;s<10;s=s+1) raw[s]<=0;
            for(integer i=0;i<N_PTS;i=i+1) begin
                for(integer s=0;s<5;s=s+1) prefix[s][i]<=0;
                product1[i]<=0; product2[i]<=0; product3[i]<=0;
                lane_integral[i]<=0; corrected[i]<=0;
            end
        end else begin
            raw[0]<=samples_i;
            enabled<={enabled[8:0],enable_i};
            cleared<={cleared[8:0],clear_i};
            active<={active[8:0],active_i};
            valid<={valid[8:0],valid_i};
            for(integer s=1;s<10;s=s+1) raw[s]<=raw[s-1];
            
            if(valid_i) previous<=signed_steps[N_PTS-1];
            for(integer i=0;i<N_PTS;i=i+1) begin
                prefix[0][i]<=$signed(signed_steps[i]) + ((i==0) ? (clear_i ? 49'sd0 : previous) : $signed(signed_steps[i-1]));
                for(integer s=1;s<5;s=s+1) begin
                    if(i >= (1 << (s-1)))
                        prefix[s][i]<=prefix[s-1][i]+prefix[s-1][i-(1 << (s-1))];
                    else prefix[s][i]<=prefix[s-1][i];
                end
                product1[i]<=prefix[4][i];
                product2[i]<=product1[i]; product3[i]<=product2[i];
                lane_integral[i]<=acc_sat({base[71],base}+
                    {{(73-MW){product3[i][MW-1]}},product3[i]});
                corrected[i]<=acc_sat($signed({lane_integral[i][71],lane_integral[i]})+($signed({{57{raw[8][16*i+15]}},raw[8][16*i+:16]}) <<< 48));
                if(valid[9] && active[9]) begin
                    samples_o[16*i+:16]<=enabled[9] ? dac_sat(corrected[i]) : raw[9][16*i+:16];
                    if(enabled[9] && ((corrected[i] >>> 48)>32764 || (corrected[i] >>> 48)<-32768))
                        clipped_o<=1;
                end else samples_o[16*i+:16]<=0;
            end
            if(valid[7] && enabled[7] && active[7]) begin
                integral<=acc_sat(next_sum);
                if(next_sum[72]!=next_sum[71]) clipped_o<=1;
            end else if(cleared[7]) integral<=0;
            if(cleared[9]) clipped_o<=0;
            valid_o<=valid[9];
        end
    end
endmodule
`default_nettype wire
