# Generated parameter bindings for the IQ64 IP.
proc init_gui { IPINST } {
  ipgui::add_param $IPINST -name "Component_Name"
  ipgui::add_param $IPINST -name "TARGET_SLAVE_BASE_ADDR"
  ipgui::add_param $IPINST -name "ID_WIDTH"
  ipgui::add_param $IPINST -name "S_AXIS_DATA_WIDTH"
  ipgui::add_param $IPINST -name "M_AXI_DATA_WIDTH"
  ipgui::add_param $IPINST -name "FIFO_ADDR_WIDTH"
  ipgui::add_param $IPINST -name "TRIGGER_QUEUE_ADDR_WIDTH"
  ipgui::add_param $IPINST -name "DEFAULT_TRIGGER_DELAY_CYCLES"
  ipgui::add_param $IPINST -name "IQ_COMPONENT_BITS"
  ipgui::add_param $IPINST -name "IQ_SCALE_LOG2"
  ipgui::add_param $IPINST -name "FORMAT_VERSION"
}
proc update_PARAM_VALUE.TARGET_SLAVE_BASE_ADDR { PARAM_VALUE.TARGET_SLAVE_BASE_ADDR } {}
proc validate_PARAM_VALUE.TARGET_SLAVE_BASE_ADDR { PARAM_VALUE.TARGET_SLAVE_BASE_ADDR } { return true }
proc update_MODELPARAM_VALUE.TARGET_SLAVE_BASE_ADDR { MODELPARAM_VALUE.TARGET_SLAVE_BASE_ADDR PARAM_VALUE.TARGET_SLAVE_BASE_ADDR } {
  set_property value [get_property value ${PARAM_VALUE.TARGET_SLAVE_BASE_ADDR}] ${MODELPARAM_VALUE.TARGET_SLAVE_BASE_ADDR}
}
proc update_PARAM_VALUE.ID_WIDTH { PARAM_VALUE.ID_WIDTH } {}
proc validate_PARAM_VALUE.ID_WIDTH { PARAM_VALUE.ID_WIDTH } { return true }
proc update_MODELPARAM_VALUE.ID_WIDTH { MODELPARAM_VALUE.ID_WIDTH PARAM_VALUE.ID_WIDTH } {
  set_property value [get_property value ${PARAM_VALUE.ID_WIDTH}] ${MODELPARAM_VALUE.ID_WIDTH}
}
proc update_PARAM_VALUE.S_AXIS_DATA_WIDTH { PARAM_VALUE.S_AXIS_DATA_WIDTH } {}
proc validate_PARAM_VALUE.S_AXIS_DATA_WIDTH { PARAM_VALUE.S_AXIS_DATA_WIDTH } { return true }
proc update_MODELPARAM_VALUE.S_AXIS_DATA_WIDTH { MODELPARAM_VALUE.S_AXIS_DATA_WIDTH PARAM_VALUE.S_AXIS_DATA_WIDTH } {
  set_property value [get_property value ${PARAM_VALUE.S_AXIS_DATA_WIDTH}] ${MODELPARAM_VALUE.S_AXIS_DATA_WIDTH}
}
proc update_PARAM_VALUE.M_AXI_DATA_WIDTH { PARAM_VALUE.M_AXI_DATA_WIDTH } {}
proc validate_PARAM_VALUE.M_AXI_DATA_WIDTH { PARAM_VALUE.M_AXI_DATA_WIDTH } { return true }
proc update_MODELPARAM_VALUE.M_AXI_DATA_WIDTH { MODELPARAM_VALUE.M_AXI_DATA_WIDTH PARAM_VALUE.M_AXI_DATA_WIDTH } {
  set_property value [get_property value ${PARAM_VALUE.M_AXI_DATA_WIDTH}] ${MODELPARAM_VALUE.M_AXI_DATA_WIDTH}
}
proc update_PARAM_VALUE.FIFO_ADDR_WIDTH { PARAM_VALUE.FIFO_ADDR_WIDTH } {}
proc validate_PARAM_VALUE.FIFO_ADDR_WIDTH { PARAM_VALUE.FIFO_ADDR_WIDTH } { return true }
proc update_MODELPARAM_VALUE.FIFO_ADDR_WIDTH { MODELPARAM_VALUE.FIFO_ADDR_WIDTH PARAM_VALUE.FIFO_ADDR_WIDTH } {
  set_property value [get_property value ${PARAM_VALUE.FIFO_ADDR_WIDTH}] ${MODELPARAM_VALUE.FIFO_ADDR_WIDTH}
}
proc update_PARAM_VALUE.TRIGGER_QUEUE_ADDR_WIDTH { PARAM_VALUE.TRIGGER_QUEUE_ADDR_WIDTH } {}
proc validate_PARAM_VALUE.TRIGGER_QUEUE_ADDR_WIDTH { PARAM_VALUE.TRIGGER_QUEUE_ADDR_WIDTH } { return true }
proc update_MODELPARAM_VALUE.TRIGGER_QUEUE_ADDR_WIDTH { MODELPARAM_VALUE.TRIGGER_QUEUE_ADDR_WIDTH PARAM_VALUE.TRIGGER_QUEUE_ADDR_WIDTH } {
  set_property value [get_property value ${PARAM_VALUE.TRIGGER_QUEUE_ADDR_WIDTH}] ${MODELPARAM_VALUE.TRIGGER_QUEUE_ADDR_WIDTH}
}
proc update_PARAM_VALUE.DEFAULT_TRIGGER_DELAY_CYCLES { PARAM_VALUE.DEFAULT_TRIGGER_DELAY_CYCLES } {}
proc validate_PARAM_VALUE.DEFAULT_TRIGGER_DELAY_CYCLES { PARAM_VALUE.DEFAULT_TRIGGER_DELAY_CYCLES } { return true }
proc update_MODELPARAM_VALUE.DEFAULT_TRIGGER_DELAY_CYCLES { MODELPARAM_VALUE.DEFAULT_TRIGGER_DELAY_CYCLES PARAM_VALUE.DEFAULT_TRIGGER_DELAY_CYCLES } {
  set_property value [get_property value ${PARAM_VALUE.DEFAULT_TRIGGER_DELAY_CYCLES}] ${MODELPARAM_VALUE.DEFAULT_TRIGGER_DELAY_CYCLES}
}
proc update_PARAM_VALUE.IQ_COMPONENT_BITS { PARAM_VALUE.IQ_COMPONENT_BITS } {}
proc validate_PARAM_VALUE.IQ_COMPONENT_BITS { PARAM_VALUE.IQ_COMPONENT_BITS } { return true }
proc update_MODELPARAM_VALUE.IQ_COMPONENT_BITS { MODELPARAM_VALUE.IQ_COMPONENT_BITS PARAM_VALUE.IQ_COMPONENT_BITS } {
  set_property value [get_property value ${PARAM_VALUE.IQ_COMPONENT_BITS}] ${MODELPARAM_VALUE.IQ_COMPONENT_BITS}
}
proc update_PARAM_VALUE.IQ_SCALE_LOG2 { PARAM_VALUE.IQ_SCALE_LOG2 } {}
proc validate_PARAM_VALUE.IQ_SCALE_LOG2 { PARAM_VALUE.IQ_SCALE_LOG2 } { return true }
proc update_MODELPARAM_VALUE.IQ_SCALE_LOG2 { MODELPARAM_VALUE.IQ_SCALE_LOG2 PARAM_VALUE.IQ_SCALE_LOG2 } {
  set_property value [get_property value ${PARAM_VALUE.IQ_SCALE_LOG2}] ${MODELPARAM_VALUE.IQ_SCALE_LOG2}
}
proc update_PARAM_VALUE.FORMAT_VERSION { PARAM_VALUE.FORMAT_VERSION } {}
proc validate_PARAM_VALUE.FORMAT_VERSION { PARAM_VALUE.FORMAT_VERSION } { return true }
proc update_MODELPARAM_VALUE.FORMAT_VERSION { MODELPARAM_VALUE.FORMAT_VERSION PARAM_VALUE.FORMAT_VERSION } {
  set_property value [get_property value ${PARAM_VALUE.FORMAT_VERSION}] ${MODELPARAM_VALUE.FORMAT_VERSION}
}
